/**
 * Verizon ThingSpace Quality of Service API endpointsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ExclusionsController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('ExclusionsController', () => {
  let controller : ExclusionsController;

  beforeAll(() => {
    controller = new ExclusionsController(testClient);
  });

  it('should Test DevicesLocationGiveConsentAsync', async () => {
    const response = await makeApiCall(
      () => controller.devicesLocationGiveConsentAsync(undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
