/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ConnectivityManagementResult
 */
interface ConnectivityManagementResult {
  /** Code of the error. */
  errorCode?: string;
  /** Details of the error. */
  errorMessage?: string;
}

export class ConnectivityManagementResultError extends ApiError<ConnectivityManagementResult> {}
