/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { EdgeDiscoveryResultData } from '../models/edgeDiscoveryResultData';

/**
 * Creates an instance of EdgeDiscoveryResult
 */
interface EdgeDiscoveryResult {
  /** HTTP status code or status of response. */
  status: string;
  /** Error details. */
  message: string;
  /** For cases where user input exceeds the boundary values an additional 'data' key will be returned with a relevant description. */
  data?: EdgeDiscoveryResultData;
}

export class EdgeDiscoveryResultError extends ApiError<EdgeDiscoveryResult> {}
