/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of SecurityResult
 */
interface SecurityResult {
  errorCode?: string;
  errorMessage?: string;
  errorUrl?: string;
}

export class SecurityResultError extends ApiError<SecurityResult> {}
