/**
 * Verizon ThingSpace Quality of Service API endpointsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  AccountConsentCreate,
  accountConsentCreateSchema,
} from '../models/accountConsentCreate';
import {
  ConsentTransactionID,
  consentTransactionIDSchema,
} from '../models/consentTransactionID';
import { optional } from '../schema';
import { BaseController } from './baseController';
import { DeviceLocationResultError } from '../errors/deviceLocationResultError';

export class ExclusionsController extends BaseController {
  /**
   * Create a consent record to use location services as an asynchronous request.
   *
   * @param body         Account details to create a consent record.
   * @return Response from the API call
   */
  async devicesLocationGiveConsentAsync(
    body?: AccountConsentCreate,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ConsentTransactionID>> {
    const req = this.createRequest('POST', '/devicelocations/action/consents');
    const mapped = req.prepareArgs({
      body: [body, optional(accountConsentCreateSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.defaultToError(DeviceLocationResultError, 'Unexpected error.');
    req.authenticate([{ thingspaceOauth: true, vzM2mSessionToken: true }]);
    return req.callAsJson(consentTransactionIDSchema, requestOptions);
  }
}
