/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { State, stateSchema } from './state';

/** Service associated with the account. */
export interface AccountService {
  /** The name of the service plan. */
  name?: string;
  /** The description of the service plan. */
  description?: string;
  /** The state of the service plan. */
  states?: State[];
}

export const accountServiceSchema: Schema<AccountService> = object({
  name: ['name', optional(string())],
  description: ['description', optional(string())],
  states: ['states', optional(array(lazy(() => stateSchema)))],
});
