/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface AccountConsentUpdate {
  /** The numeric name of the account, including leading zeros. */
  accountName?: string;
  /** The consent setting to use for all the devices in the account. */
  allDeviceConsent?: number;
}

export const accountConsentUpdateSchema: Schema<AccountConsentUpdate> = object({
  accountName: ['accountName', optional(string())],
  allDeviceConsent: ['allDeviceConsent', optional(number())],
});
