/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, optional, Schema } from '../schema';
import { AccountLead, accountLeadSchema } from './accountLead';

/** Returns information for all leads associated with an account. */
export interface AccountLeadsResult {
  /** False if no more leads.True if there is more data to be retrieved. */
  hasMoreData?: boolean;
  /** The leads associated with an account. */
  leads?: AccountLead[];
}

export const accountLeadsResultSchema: Schema<AccountLeadsResult> = object({
  hasMoreData: ['hasMoreData', optional(boolean())],
  leads: ['leads', optional(array(lazy(() => accountLeadSchema)))],
});
