/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { DeviceId, deviceIdSchema } from './deviceId';

/** A list of deviceId objects to use when requesting information from multiple devices. */
export interface AccountDeviceList {
  /** All identifiers for the device. */
  deviceIds?: DeviceId[];
}

export const accountDeviceListSchema: Schema<AccountDeviceList> = object({
  deviceIds: ['deviceIds', optional(array(lazy(() => deviceIdSchema)))],
});
