/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Address, addressSchema } from './address';

/** A successful response returns an array of lead objects. */
export interface AccountLead {
  /** The customer address for the line's primary place of use, for line usage taxation. */
  address?: Address;
  /** Unique number for each lead. Use this value in the leadId parameter when activating devices to credit the activations to the lead. */
  leadId?: string;
  /** The current state of the lead, such as “Qualified” or “Closed.” */
  leadState?: string;
}

export const accountLeadSchema: Schema<AccountLead> = object({
  address: ['address', optional(lazy(() => addressSchema))],
  leadId: ['leadId', optional(string())],
  leadState: ['leadState', optional(string())],
});
