/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  ActionAccountGroupShare,
  actionAccountGroupShareSchema,
} from './actionAccountGroupShare';
import {
  ConditionAccountGroupShare,
  conditionAccountGroupShareSchema,
} from './conditionAccountGroupShare';
import {
  FilterCriteriaAccountGroupShare,
  filterCriteriaAccountGroupShareSchema,
} from './filterCriteriaAccountGroupShare';

export interface AccountGroupShareIndividual {
  filterCriteria?: FilterCriteriaAccountGroupShare;
  condition?: ConditionAccountGroupShare;
  action?: ActionAccountGroupShare;
}

export const accountGroupShareIndividualSchema: Schema<AccountGroupShareIndividual> = object(
  {
    filterCriteria: [
      'filterCriteria',
      optional(lazy(() => filterCriteriaAccountGroupShareSchema)),
    ],
    condition: [
      'condition',
      optional(lazy(() => conditionAccountGroupShareSchema)),
    ],
    action: ['action', optional(lazy(() => actionAccountGroupShareSchema))],
  }
);
