/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

/** Whether the trigger is active or not. */
export interface ActiveTriggerIndicator {
  /** Indicates if the trigger is active<br />True - trigger is active<br />False - trigger is not active. */
  active?: boolean;
}

export const activeTriggerIndicatorSchema: Schema<ActiveTriggerIndicator> = object(
  { active: ['active', optional(boolean())] }
);
