/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ChangePlan, changePlanSchema } from './changePlan';

export interface ActionAccountGroupShare {
  changePlan?: ChangePlan;
}

export const actionAccountGroupShareSchema: Schema<ActionAccountGroupShare> = object(
  { changePlan: ['changePlan', optional(lazy(() => changePlanSchema))] }
);
