/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { DeviceId, deviceIdSchema } from './deviceId';

/** Contains the device identifiers and a success or failure response for each device in the request. */
export interface AddDevicesResult {
  /** Identifiers for the device. */
  deviceIds?: DeviceId[];
  /** The success message or error message for the current device. */
  response?: string;
}

export const addDevicesResultSchema: Schema<AddDevicesResult> = object({
  deviceIds: ['deviceIds', optional(array(lazy(() => deviceIdSchema)))],
  response: ['response', optional(string())],
});
