/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface AdvanceConfiguration {
  serviceRoleArn?: string;
  serviceRolePermissionBoundary?: string;
  enableProxy?: boolean;
  httpProxy?: string;
  httpsProxy?: string;
  noProxy?: string;
  proxyRootCA?: string;
  enableTlsTraffic?: boolean;
  enableAutoApprove?: boolean;
  enableMultiMaster?: boolean;
  enableDedicatedMaster?: boolean;
}

export const advanceConfigurationSchema: Schema<AdvanceConfiguration> = object({
  serviceRoleArn: ['serviceRoleArn', optional(string())],
  serviceRolePermissionBoundary: [
    'serviceRolePermissionBoundary',
    optional(string()),
  ],
  enableProxy: ['enableProxy', optional(boolean())],
  httpProxy: ['httpProxy', optional(string())],
  httpsProxy: ['httpsProxy', optional(string())],
  noProxy: ['noProxy', optional(string())],
  proxyRootCA: ['proxyRootCA', optional(string())],
  enableTlsTraffic: ['enableTlsTraffic', optional(boolean())],
  enableAutoApprove: ['enableAutoApprove', optional(boolean())],
  enableMultiMaster: ['enableMultiMaster', optional(boolean())],
  enableDedicatedMaster: ['enableDedicatedMaster', optional(boolean())],
});
