/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string, unknown } from '../schema';

/** Contains usage information per device. */
export interface AggregateUsageItem {
  /** International Mobile Equipment Identifier. This is the ID of the device reporting usage. */
  imei?: string;
  /** Number of sessions established by the device reporting usage. */
  numberOfSessions?: number;
  /** The amount of data transferred by the device reporting usage, measured in Bytes. */
  bytesTransferred?: number;
  example?: unknown;
}

export const aggregateUsageItemSchema: Schema<AggregateUsageItem> = object({
  imei: ['imei', optional(string())],
  numberOfSessions: ['numberOfSessions', optional(number())],
  bytesTransferred: ['bytesTransferred', optional(number())],
  example: ['example', optional(unknown())],
});
