/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  TriggersListOptions,
  triggersListOptionsSchema,
} from './triggersListOptions';

/** A result containing a list of anomaly triggers. */
export interface AnomalyTriggerResult {
  /** Trigger value chunk details. */
  triggers?: TriggersListOptions[];
}

export const anomalyTriggerResultSchema: Schema<AnomalyTriggerResult> = object({
  triggers: [
    'triggers',
    optional(array(lazy(() => triggersListOptionsSchema))),
  ],
});
