/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Trigger for anomaly detection. */
export interface AnomalyDetectionTrigger {
  /** Trigger ID to identify the request in a callback. */
  triggerId?: string;
}

export const anomalyDetectionTriggerSchema: Schema<AnomalyDetectionTrigger> = object(
  { triggerId: ['triggerId', optional(string())] }
);
