/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { ResponseCodeEnum, responseCodeEnumSchema } from './responseCodeEnum';

/** ResponseCode and/or a message indicating success or failure of the request. */
export interface ApiResponseCode {
  /** Possible response codes. */
  responseCode: ResponseCodeEnum;
  /** More details about the responseCode received. */
  message: string;
}

export const apiResponseCodeSchema: Schema<ApiResponseCode> = object({
  responseCode: ['responseCode', responseCodeEnumSchema],
  message: ['message', string()],
});
