/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { AccountLabels, accountLabelsSchema } from './accountLabels';

export interface AssociateLabelRequest {
  /** The name of a billing account. An account name is usually numeric, and must include any leading zeros. */
  accountName?: string;
  /** Maximum of 2,000 objects are allowed in the array. */
  labels?: AccountLabels;
}

export const associateLabelRequestSchema: Schema<AssociateLabelRequest> = object(
  {
    accountName: ['accountName', optional(string())],
    labels: ['labels', optional(lazy(() => accountLabelsSchema))],
  }
);
