/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Information related to manage resources in Azure infrastructure. */
export interface AzureCspProfile {
  /** Azure tenant ID. */
  tenantID?: string;
  /** Azure subscription ID. */
  subscriptionID?: string;
  /** Azure client ID. */
  clientId?: string;
  /** Azure client secret. */
  clientSecret?: string;
}

export const azureCspProfileSchema: Schema<AzureCspProfile> = object({
  tenantID: ['tenantID', optional(string())],
  subscriptionID: ['subscriptionID', optional(string())],
  clientId: ['clientId', optional(string())],
  clientSecret: ['clientSecret', optional(string())],
});
