/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { BillingCycle, billingCycleSchema } from './billingCycle';
import { DeviceList, deviceListSchema } from './deviceList';
import { LabelsList, labelsListSchema } from './labelsList';

/** Information required to associate a usage segmentation label with a device to retrieve billing. */
export interface BilledusageListRequest {
  accountName?: string;
  labels?: LabelsList;
  devices?: DeviceList[];
  billingCycle?: BillingCycle;
}

export const billedusageListRequestSchema: Schema<BilledusageListRequest> = object(
  {
    accountName: ['accountName', optional(string())],
    labels: ['labels', optional(lazy(() => labelsListSchema))],
    devices: ['devices', optional(array(lazy(() => deviceListSchema)))],
    billingCycle: ['BillingCycle', optional(lazy(() => billingCycleSchema))],
  }
);
