/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

/** Bill usage request. */
export interface BillUsageRequest {
  /** Account identifier. */
  accountName?: string;
  /** Start date to search for billable usage, mm-dd-yyyy. */
  startDate?: string;
  /** End date to search for billable usage, mm-dd-yyyy. */
  endDate?: string;
  /** Request usage for single or multiple accounts. */
  usageForAllAccounts?: boolean;
}

export const billUsageRequestSchema: Schema<BillUsageRequest> = object({
  accountName: ['accountName', optional(string())],
  startDate: ['startDate', optional(string())],
  endDate: ['endDate', optional(string())],
  usageForAllAccounts: ['usageForAllAccounts', optional(boolean())],
});
