/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';
import {
  CSPCompatibilityEnum,
  cSPCompatibilityEnumSchema,
} from './cSPCompatibilityEnum';

/** Deployment boundary of a service. */
export interface Boundary {
  /** Cloud service provider e.g. AWS_PUBLIC_CLOUD, AWS_WL, AWS_OUTPOST, AZURE_EDGE, AZURE_PUBLIC_CLOUD. */
  csp?: CSPCompatibilityEnum;
  /** Boundary region e.g. US East (Ohio). */
  region?: string;
  /** Zones listed under a specific region. */
  zoneId?: string[];
}

export const boundarySchema: Schema<Boundary> = object({
  csp: ['csp', optional(cSPCompatibilityEnumSchema)],
  region: ['region', optional(string())],
  zoneId: ['zoneId', optional(array(string()))],
});
