/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ApiResponseCode, apiResponseCodeSchema } from './apiResponseCode';
import {
  DeviceServiceInformation,
  deviceServiceInformationSchema,
} from './deviceServiceInformation';

/** Status of Hyper Precise Location on the device. */
export interface BullseyeServiceResult {
  /** The account the device belongs to. */
  accountNumber?: string;
  /** List of devices. */
  deviceList?: DeviceServiceInformation[];
  /** ResponseCode and/or a message indicating success or failure of the request. */
  responseType?: ApiResponseCode;
}

export const bullseyeServiceResultSchema: Schema<BullseyeServiceResult> = object(
  {
    accountNumber: ['accountNumber', optional(string())],
    deviceList: [
      'deviceList',
      optional(array(lazy(() => deviceServiceInformationSchema))),
    ],
    responseType: ['responseType', optional(lazy(() => apiResponseCodeSchema))],
  }
);
