/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CallbackServiceEnum
 */
export enum CallbackServiceEnum {
  Fota = 'Fota',
}

/**
 * Schema for CallbackServiceEnum
 */
export const callbackServiceEnumSchema: Schema<CallbackServiceEnum> = stringEnum(CallbackServiceEnum);
