/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CallbackServiceNameEnum
 */
export enum CallbackServiceNameEnum {
  Location = 'Location',
  DeviceLocation = 'DeviceLocation',
}

/**
 * Schema for CallbackServiceNameEnum
 */
export const callbackServiceNameEnumSchema: Schema<CallbackServiceNameEnum> = stringEnum(CallbackServiceNameEnum);
