/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { V3TimeWindow, v3TimeWindowSchema } from './v3TimeWindow';

/** Firmware upgrade for devices. */
export interface CampaignFirmwareUpgrade {
  /** Campaign name. */
  campaignName?: string;
  /** Firmware name to upgrade to. */
  firmwareName: string;
  /** Old firmware version. */
  firmwareFrom: string;
  /** New firmware version. */
  firmwareTo: string;
  /** Valid values include: LWM2M, OMA and HTTP. */
  protocol: string;
  /** Campaign start date. */
  startDate: string;
  /** Campaign end date. */
  endDate: string;
  /** List of allowed campaign time windows. */
  campaignTimeWindowList?: V3TimeWindow[];
  /** Device IMEI list. */
  deviceList: string[];
}

export const campaignFirmwareUpgradeSchema: Schema<CampaignFirmwareUpgrade> = object(
  {
    campaignName: ['campaignName', optional(string())],
    firmwareName: ['firmwareName', string()],
    firmwareFrom: ['firmwareFrom', string()],
    firmwareTo: ['firmwareTo', string()],
    protocol: ['protocol', string()],
    startDate: ['startDate', string()],
    endDate: ['endDate', string()],
    campaignTimeWindowList: [
      'campaignTimeWindowList',
      optional(array(lazy(() => v3TimeWindowSchema))),
    ],
    deviceList: ['deviceList', array(string())],
  }
);
