/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CampaignStatusEnum
 */
export enum CampaignStatusEnum {
  CampaignRequestPending = 'CampaignRequestPending',
  CampaignRequestFailed = 'CampaignRequestFailed',
  CampaignRequestQueued = 'CampaignRequestQueued',
  CampaignCancelled = 'CampaignCancelled',
  CampaignAborted = 'CampaignAborted',
  CampaignFailed = 'CampaignFailed',
  CampaignScheduled = 'CampaignScheduled',
  CampaignEnded = 'CampaignEnded',
}

/**
 * Schema for CampaignStatusEnum
 */
export const campaignStatusEnumSchema: Schema<CampaignStatusEnum> = stringEnum(CampaignStatusEnum);
