/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CarrierServicePlan {
  /** The name of the service plan */
  name?: string;
  /** The inventory name or system name of the service plan */
  code?: string;
  /** The ammount of space the service plan will occupy on the Subscriber Information Module (SIM) */
  sizeKb?: string;
  /** The billing record ID. This can be numeric, alpha or alphanumeric. */
  carrierServicePlanCode?: string;
}

export const carrierServicePlanSchema: Schema<CarrierServicePlan> = object({
  name: ['name', optional(string())],
  code: ['code', optional(string())],
  sizeKb: ['sizeKb', optional(string())],
  carrierServicePlanCode: ['carrierServicePlanCode', optional(string())],
});
