/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

/** A user can create a category and use the same during service creation request. */
export interface Category {
  /** Auto-generated unique Id eg: 58296746-57ee-44f8-8107-399b61d53967. */
  id?: string;
  /** Any string value which is described as a category name. */
  categoryName: string;
  /** Brief description about the category being created. */
  categoryDescription?: string;
  /** Boolean value which implies if the category is verizon certified or not by default it is false. */
  isVerizonCertified?: boolean;
  /** System captured creation date and time when tag is created. */
  createdDate?: string;
  /** System captured date and time when the tag was last modified. */
  lastModifiedDate?: string;
  /** User information who created the tag. */
  createdBy?: string;
  /** Last user information who made changes to tag. */
  updatedBy?: string;
}

export const categorySchema: Schema<Category> = object({
  id: ['id', optional(string())],
  categoryName: ['categoryName', string()],
  categoryDescription: ['categoryDescription', optional(string())],
  isVerizonCertified: ['isVerizonCertified', optional(boolean())],
  createdDate: ['createdDate', optional(string())],
  lastModifiedDate: ['lastModifiedDate', optional(string())],
  createdBy: ['createdBy', optional(string())],
  updatedBy: ['updatedBy', optional(string())],
});
