/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Response to change PWN device ip address. */
export interface ChangePWNDeviceIpaddressResponse {
  /** A unique string that associates the request with the results that are sent via a callback service. */
  requestId?: string;
}

export const changePWNDeviceIpaddressResponseSchema: Schema<ChangePWNDeviceIpaddressResponse> = object(
  { requestId: ['requestId', optional(string())] }
);
