/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Response to change mec device profile */
export interface ChangeMecDeviceProfileResponse {
  /** A unique string that associates the request with the results that are sent via a callback service. */
  requestId?: string;
}

export const changeMecDeviceProfileResponseSchema: Schema<ChangeMecDeviceProfileResponse> = object(
  { requestId: ['requestId', optional(string())] }
);
