/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { PWNDeviceList, pWNDeviceListSchema } from './pWNDeviceList';

export interface ChangePWNDeviceStateDeactivateRequest {
  accountName: string;
  deviceList: PWNDeviceList[];
}

export const changePWNDeviceStateDeactivateRequestSchema: Schema<ChangePWNDeviceStateDeactivateRequest> = object(
  {
    accountName: ['accountName', string()],
    deviceList: ['deviceList', array(lazy(() => pWNDeviceListSchema))],
  }
);
