/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { MECDeviceList, mECDeviceListSchema } from './mECDeviceList';

export interface ChangePmecDeviceIPaddressBulkRequest {
  accountName: string;
  deviceList: MECDeviceList[];
}

export const changePmecDeviceIPaddressBulkRequestSchema: Schema<ChangePmecDeviceIPaddressBulkRequest> = object(
  {
    accountName: ['accountName', string()],
    deviceList: ['deviceList', array(lazy(() => mECDeviceListSchema))],
  }
);
