/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { PWNDeviceList, pWNDeviceListSchema } from './pWNDeviceList';

export interface ChangePWNDeviceProfileRequest {
  accountName: string;
  deviceList: PWNDeviceList[];
  newProfile: string;
}

export const changePWNDeviceProfileRequestSchema: Schema<ChangePWNDeviceProfileRequest> = object(
  {
    accountName: ['accountName', string()],
    deviceList: ['deviceList', array(lazy(() => pWNDeviceListSchema))],
    newProfile: ['newProfile', string()],
  }
);
