/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { MECDeviceList, mECDeviceListSchema } from './mECDeviceList';

export interface ChangePmecDeviceProfileRequest {
  accountName: string;
  deviceList: MECDeviceList[];
  newProfile: string;
}

export const changePmecDeviceProfileRequestSchema: Schema<ChangePmecDeviceProfileRequest> = object(
  {
    accountName: ['accountName', string()],
    deviceList: ['deviceList', array(lazy(() => mECDeviceListSchema))],
    newProfile: ['newProfile', string()],
  }
);
