/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { SharePlan, sharePlanSchema } from './sharePlan';

export interface ChangePlan {
  triggerDate?: string;
  sharePlan?: SharePlan[];
}

export const changePlanSchema: Schema<ChangePlan> = object({
  triggerDate: ['triggerDate', optional(string())],
  sharePlan: ['sharePlan', optional(array(lazy(() => sharePlanSchema)))],
});
