/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import { ClaimStatusEnum, claimStatusEnumSchema } from './claimStatusEnum';

/** Current status of the claim can have only two values eg: VERIFIED/UNVERIFIED. */
export interface ClaimStatusRequest {
  /** Current status of the claim can have only two values eg: VERIFIED/UNVERIFIED. */
  claimStatus?: ClaimStatusEnum;
}

export const claimStatusRequestSchema: Schema<ClaimStatusRequest> = object({
  claimStatus: ['claimStatus', optional(claimStatusEnumSchema)],
});
