/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  ClusterProvisioning,
  clusterProvisioningSchema,
} from './clusterProvisioning';
import { DataBackup, dataBackupSchema } from './dataBackup';

export interface CloudCredential {
  /** Name of the credentials. */
  name?: string;
  clusterProvisioning?: ClusterProvisioning;
  dataBackup?: DataBackup;
}

export const cloudCredentialSchema: Schema<CloudCredential> = object({
  name: ['name', optional(string())],
  clusterProvisioning: [
    'clusterProvisioning',
    optional(lazy(() => clusterProvisioningSchema)),
  ],
  dataBackup: ['dataBackup', optional(lazy(() => dataBackupSchema))],
});
