/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ClusterTypeEnum
 */
export enum ClusterTypeEnum {
  PublicCloud = 'publicCloud',
  DataCenter = 'dataCenter',
}

/**
 * Schema for ClusterTypeEnum
 */
export const clusterTypeEnumSchema: Schema<ClusterTypeEnum> = stringEnum(ClusterTypeEnum);
