/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ClusterStateEnum
 */
export enum ClusterStateEnum {
  READY = 'READY',
  NOTREADY = 'NOT_READY',
}

/**
 * Schema for ClusterStateEnum
 */
export const clusterStateEnumSchema: Schema<ClusterStateEnum> = stringEnum(ClusterStateEnum);
