/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ClusterProviderEnum
 */
export enum ClusterProviderEnum {
  AWS = 'AWS',
  GCP = 'GCP',
  AZURE = 'AZURE',
}

/**
 * Schema for ClusterProviderEnum
 */
export const clusterProviderEnumSchema: Schema<ClusterProviderEnum> = stringEnum(ClusterProviderEnum);
