/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { ClusterSpec, clusterSpecSchema } from './clusterSpec';
import { ClusterStatus, clusterStatusSchema } from './clusterStatus';
import { Metadata, metadataSchema } from './metadata';

export interface Cluster {
  apiVersion?: string;
  kind?: string;
  metadata?: Metadata;
  spec?: ClusterSpec;
  status?: ClusterStatus;
}

export const clusterSchema: Schema<Cluster> = object({
  apiVersion: ['apiVersion', optional(string())],
  kind: ['kind', optional(string())],
  metadata: ['metadata', optional(lazy(() => metadataSchema))],
  spec: ['spec', optional(lazy(() => clusterSpecSchema))],
  status: ['status', optional(lazy(() => clusterStatusSchema))],
});
