/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ConfigFileItem {
  id?: string;
}

export const configFileItemSchema: Schema<ConfigFileItem> = object({
  id: ['id', optional(string())],
});
