/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The transaction ID of the request that you want to cancel, from the POST /devicelocations synchronus response. */
export interface ConsentTransactionID {
  transactionId?: string;
  status?: string;
}

export const consentTransactionIDSchema: Schema<ConsentTransactionID> = object({
  transactionId: ['transactionId', optional(string())],
  status: ['status', optional(string())],
});
