/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { FieldsHttpHeaders, fieldsHttpHeadersSchema } from './fieldsHttpHeaders';

export interface CreateTargetRequestFields {
  httpheaders?: FieldsHttpHeaders;
  /** List of device types. */
  devicetypes?: string[];
}

export const createTargetRequestFieldsSchema: Schema<CreateTargetRequestFields> = object(
  {
    httpheaders: ['httpheaders', optional(lazy(() => fieldsHttpHeadersSchema))],
    devicetypes: ['devicetypes', optional(array(string()))],
  }
);
