/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** A successful request returns a serviceProfileId that you can use in subsequent requests. */
export interface CreateServiceProfileResult {
  /** Unique identifier for a service profile. */
  serviceProfileId?: string;
}

export const createServiceProfileResultSchema: Schema<CreateServiceProfileResult> = object(
  { serviceProfileId: ['serviceProfileId', optional(string())] }
);
