/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CredentialsTypeEnum
 */
export enum CredentialsTypeEnum {
  UserPassCredentials = 'UserPassCredentials',
  SSHCredentials = 'SSHCredentials',
}

/**
 * Schema for CredentialsTypeEnum
 */
export const credentialsTypeEnumSchema: Schema<CredentialsTypeEnum> = stringEnum(CredentialsTypeEnum);
