/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CSPCompatibilityEnum
 */
export enum CSPCompatibilityEnum {
  AWSPUBLICCLOUD = 'AWS_PUBLIC_CLOUD',
  AWSWL = 'AWS_WL',
  AWSOUTPOST = 'AWS_OUTPOST',
  AZUREPUBLICCLOUD = 'AZURE_PUBLIC_CLOUD',
  AZUREEDGE = 'AZURE_EDGE',
}

/**
 * Schema for CSPCompatibilityEnum
 */
export const cSPCompatibilityEnumSchema: Schema<CSPCompatibilityEnum> = stringEnum(CSPCompatibilityEnum);
