/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { CSPProfile, cSPProfileSchema } from './cSPProfile';

/** Response to CSP profile list. */
export interface CSPProfileData {
  /** Total number of records available. */
  count?: number;
  /** List of all available CSP profile available within the user's organization. */
  cspProfileList?: CSPProfile[];
}

export const cSPProfileDataSchema: Schema<CSPProfileData> = object({
  count: ['count', optional(number())],
  cspProfileList: [
    'cspProfileList',
    optional(array(lazy(() => cSPProfileSchema))),
  ],
});
