/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DataCenterPackageTypeEnum
 */
export enum DataCenterPackageTypeEnum {
  Linux = 'Linux',
  EnumOVAOVF = 'OVA/OVF',
  QCOW2 = 'QCOW2',
}

/**
 * Schema for DataCenterPackageTypeEnum
 */
export const dataCenterPackageTypeEnumSchema: Schema<DataCenterPackageTypeEnum> = stringEnum(DataCenterPackageTypeEnum);
