/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface DataTriggerRequest {
  comparator?: string;
  threshold?: number;
  thresholdUnit?: string;
}

export const dataTriggerRequestSchema: Schema<DataTriggerRequest> = object({
  comparator: ['comparator', optional(string())],
  threshold: ['threshold', optional(number())],
  thresholdUnit: ['thresholdUnit', optional(string())],
});
