/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DependentServicesTypeEnum
 */
export enum DependentServicesTypeEnum {
  MYSERVICE = 'MY_SERVICE',
}

/**
 * Schema for DependentServicesTypeEnum
 */
export const dependentServicesTypeEnumSchema: Schema<DependentServicesTypeEnum> = stringEnum(DependentServicesTypeEnum);
