/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DeploymentTypeEnum
 */
export enum DeploymentTypeEnum {
  PublicMEC = 'PublicMEC',
  PrivateMEC = 'PrivateMEC',
  OnPremiseMEC = 'OnPremiseMEC',
}

/**
 * Schema for DeploymentTypeEnum
 */
export const deploymentTypeEnumSchema: Schema<DeploymentTypeEnum> = stringEnum(DeploymentTypeEnum);
