/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface DeploymentLocationCluster {
  name?: string;
  id?: string;
}

export const deploymentLocationClusterSchema: Schema<DeploymentLocationCluster> = object(
  { name: ['name', optional(string())], id: ['id', optional(string())] }
);
