/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, optional, Schema } from '../schema';
import { Usage, usageSchema } from './usage';

/** Response to return the daily network data usage of a single device during a specified time period. */
export interface DeviceUsageListResult {
  /** False for a status 200 response.True for a status 202 response, indicating that there is more data to be retrieved. */
  hasMoreData?: boolean;
  /** Placeholder. */
  usageHistory?: Usage[];
}

export const deviceUsageListResultSchema: Schema<DeviceUsageListResult> = object(
  {
    hasMoreData: ['hasMoreData', optional(boolean())],
    usageHistory: ['usageHistory', optional(array(lazy(() => usageSchema)))],
  }
);
