/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Response to activate service for one or more devices so that they can send and receive data. */
export interface DeviceManagementResult {
  /** A unique string that associates the request with the results that are sent via a callback service. */
  requestId?: string;
}

export const deviceManagementResultSchema: Schema<DeviceManagementResult> = object(
  { requestId: ['requestId', optional(string())] }
);
