/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  M5gBiaddressAndcustomerinfo,
  m5gBiaddressAndcustomerinfoSchema,
} from './m5gBiaddressAndcustomerinfo';
import { M5gBideviceId1, m5gBideviceId1Schema } from './m5gBideviceId1';

export interface DeviceListWithServiceAddress {
  deviceId?: M5gBideviceId1[];
  primaryPlaceofuse?: M5gBiaddressAndcustomerinfo;
}

export const deviceListWithServiceAddressSchema: Schema<DeviceListWithServiceAddress> = object(
  {
    deviceId: ['deviceId', optional(array(lazy(() => m5gBideviceId1Schema)))],
    primaryPlaceofuse: [
      'primaryPlaceofuse',
      optional(lazy(() => m5gBiaddressAndcustomerinfoSchema)),
    ],
  }
);
