/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Search by device id. */
export interface DeviceIdSearch {
  /** The string appears anywhere in the identifer. */
  contains?: string;
  /** The identifer must start with the specified string. */
  startswith?: string;
  /** The identifier must end with the specified string. */
  endswith?: string;
  /** The type of the device identifier to match. Valid types of identifiers are:EID,ESN,ICCID,IMEI,MDN,MEID,MSISDN. */
  kind: string;
}

export const deviceIdSearchSchema: Schema<DeviceIdSearch> = object({
  contains: ['contains', optional(string())],
  startswith: ['startswith', optional(string())],
  endswith: ['endswith', optional(string())],
  kind: ['kind', string()],
});
