/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { DeviceId, deviceIdSchema } from './deviceId';

/** Request to list of network connection events for a device during a specified time period. */
export interface DeviceConnectionListRequest {
  /** An identifier for a single device. */
  deviceId?: DeviceId;
  /** The earliest date and time for which you want connection events. */
  earliest?: string;
  /** The last date and time for which you want connection events. */
  latest?: string;
}

export const deviceConnectionListRequestSchema: Schema<DeviceConnectionListRequest> = object(
  {
    deviceId: ['deviceId', optional(lazy(() => deviceIdSchema))],
    earliest: ['earliest', optional(string())],
    latest: ['latest', optional(string())],
  }
);
