/**
 * Verizon ThingSpace Quality of Service API endpointsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { DeviceId, deviceIdSchema } from './deviceId';
import { FlowInfo, flowInfoSchema } from './flowInfo';

export interface DeviceInfo {
  /** device identifiers consisting of an ID value and what that value represents (kind) */
  deviceId?: DeviceId;
  /** the IPv6 IP address of the device */
  deviceIPv6Addr?: string;
  /** The details of the data connection */
  flowInfo?: FlowInfo[];
}

export const deviceInfoSchema: Schema<DeviceInfo> = object({
  deviceId: ['deviceId', optional(lazy(() => deviceIdSchema))],
  deviceIPv6Addr: ['deviceIPv6Addr', optional(string())],
  flowInfo: ['flowInfo', optional(array(lazy(() => flowInfoSchema)))],
});
