/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { DeviceList, deviceListSchema } from './deviceList';

export interface DeviceUploadRequest {
  accountName: string;
  devices: DeviceList[];
  emailAddress: string;
  deviceSku: string;
  uploadType: string;
}

export const deviceUploadRequestSchema: Schema<DeviceUploadRequest> = object({
  accountName: ['accountName', string()],
  devices: ['devices', array(lazy(() => deviceListSchema))],
  emailAddress: ['emailAddress', string()],
  deviceSku: ['deviceSku', string()],
  uploadType: ['uploadType', string()],
});
