/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { AccountDeviceList, accountDeviceListSchema } from './accountDeviceList';

/** Request for device status to check availability of activation. */
export interface DeviceActivationRequest {
  /** The name of a billing account. */
  accountName?: string;
  /** Up to 10,000 devices that you want to move to a different account, specified by device identifier. */
  devices?: AccountDeviceList[];
}

export const deviceActivationRequestSchema: Schema<DeviceActivationRequest> = object(
  {
    accountName: ['accountName', optional(string())],
    devices: ['devices', optional(array(lazy(() => accountDeviceListSchema)))],
  }
);
