/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface DeviceIdarray {
  kind?: string;
  id?: string;
}

export const deviceIdarraySchema: Schema<DeviceIdarray> = object({
  kind: ['kind', optional(string())],
  id: ['id', optional(string())],
});
