/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { AccountDeviceList, accountDeviceListSchema } from './accountDeviceList';
import { CustomFields, customFieldsSchema } from './customFields';

/** Request to retrieve cost center value of a device. */
export interface DeviceCostCenterRequest {
  /** The name of a billing account. */
  accountName?: string;
  /** The new cost center code. Valid values are any string of up to 36 alphanumeric characters, space, dash, exclamation point, and pound sign. */
  costCenter?: string;
  /** Custom field names and values, if you want to only include devices that have matching values. */
  customFields?: CustomFields[];
  /** A list of the devices that you want to change, specified by device identifier. Do not include accountName, groupName, customFields, or servicePlan if you use this parameter. */
  devices?: AccountDeviceList[];
  /** The name of a device group, if you want to only include devices in that group. */
  groupName?: string;
  /** The customer name and the address of the device's primary place of use. These values are applied to all devices in the request.The Primary Place of Use location may affect taxation or have other legal implications. You may want to speak with legal and/or financial advisers before entering values for these fields. */
  primaryPlaceOfUse?: unknown;
  /** Set to true to remove the cost center code value. This flag takes precedence over a new costCenter value. If this flag is true and costCenter has a value, the cost center code is removed. Do not include this parameter, or set it to false to change the costCenter value. */
  removeCostCenter?: boolean;
  /** The name of a service plan, if you want to only include devices that have that service plan. */
  servicePlan?: string;
}

export const deviceCostCenterRequestSchema: Schema<DeviceCostCenterRequest> = object(
  {
    accountName: ['accountName', optional(string())],
    costCenter: ['costCenter', optional(string())],
    customFields: [
      'customFields',
      optional(array(lazy(() => customFieldsSchema))),
    ],
    devices: ['devices', optional(array(lazy(() => accountDeviceListSchema)))],
    groupName: ['groupName', optional(string())],
    primaryPlaceOfUse: ['primaryPlaceOfUse', optional(unknown())],
    removeCostCenter: ['removeCostCenter', optional(boolean())],
    servicePlan: ['servicePlan', optional(string())],
  }
);
