/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Device logging information. */
export interface DeviceLog {
  /** Device IMEI. */
  deviceId: string;
  /** Time of log. */
  logTime: string;
  /** Log type (one of SoftwareUpdate, Event, UserNotification, AgentService, Wireless, WirelessWeb, MobileBroadbandModem, WindowsMDM). */
  logType: string;
  /** Event log. */
  eventLog: string;
  /** Base64-encoded contents of binary log file. */
  binaryLogFileBase64: string;
  /** File name of binary log file. */
  binaryLogFilename: string;
}

export const deviceLogSchema: Schema<DeviceLog> = object({
  deviceId: ['deviceId', string()],
  logTime: ['logTime', string()],
  logType: ['logType', string()],
  eventLog: ['eventLog', string()],
  binaryLogFileBase64: ['binaryLogFileBase64', string()],
  binaryLogFilename: ['binaryLogFilename', string()],
});
