/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { MECDeviceId, mECDeviceIdSchema } from './mECDeviceId';

export interface DeviceList7 {
  deviceIds: MECDeviceId[];
  ipAddress: string;
}

export const deviceList7Schema: Schema<DeviceList7> = object({
  deviceIds: ['deviceIds', array(lazy(() => mECDeviceIdSchema))],
  ipAddress: ['ipAddress', string()],
});
