/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { DeviceId, deviceIdSchema } from './deviceId';
import { Label, labelSchema } from './label';

/** Request to list device aggregate usage. */
export interface DeviceAggregateUsageListRequest {
  /** The beginning of the reporting period. The startTime cannot be more than 6 months before the current date. */
  startTime: string;
  /** The end of the reporting period. The endTime date must be within on month of the startTime date. */
  endTime: string;
  /** One or more devices for which you want aggregate data, specified by device ID. */
  deviceIds?: DeviceId[];
  /** The name of a billing account. */
  accountName?: string;
  /** The name of a device group, if you want to only include devices in that group. */
  groupName?: string;
  label?: Label[];
}

export const deviceAggregateUsageListRequestSchema: Schema<DeviceAggregateUsageListRequest> = object(
  {
    startTime: ['startTime', string()],
    endTime: ['endTime', string()],
    deviceIds: ['deviceIds', optional(array(lazy(() => deviceIdSchema)))],
    accountName: ['accountName', optional(string())],
    groupName: ['groupName', optional(string())],
    label: ['label', optional(array(lazy(() => labelSchema)))],
  }
);
