/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema';
import { V3Device, v3DeviceSchema } from './v3Device';

/** Device list information. */
export interface DeviceListResult {
  /** Account name. */
  accountName: string;
  /** Total device count. */
  deviceCount: number;
  /** List of devices with id in IMEI. */
  deviceList: V3Device[];
}

export const deviceListResultSchema: Schema<DeviceListResult> = object({
  accountName: ['accountName', string()],
  deviceCount: ['deviceCount', number()],
  deviceList: ['deviceList', array(lazy(() => v3DeviceSchema))],
});
