/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { DeviceId2, deviceId2Schema } from './deviceId2';

export interface DeviceList2 {
  ids?: DeviceId2[];
}

export const deviceList2Schema: Schema<DeviceList2> = object({
  ids: ['ids', optional(array(lazy(() => deviceId2Schema)))],
});
