/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { GIODeviceList, gIODeviceListSchema } from './gIODeviceList';

export interface DeviceProfileRequest {
  devices?: GIODeviceList[];
  accountName?: string;
  servicePlan?: string;
}

export const deviceProfileRequestSchema: Schema<DeviceProfileRequest> = object({
  devices: ['devices', optional(array(lazy(() => gIODeviceListSchema)))],
  accountName: ['accountName', optional(string())],
  servicePlan: ['servicePlan', optional(string())],
});
