/**
 * Verizon ThingSpace Quality of Service API endpointsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** device identifiers consisting of an ID value and what that value represents (kind) */
export interface DeviceId {
  /** The numeric or alphanumeric ID value */
  id?: string;
  /** What the ID value represents, which could be a Mobile Directory Number (MDN) or an International Mobile Equipment Identifier (IMEI) as an example */
  kind?: string;
}

export const deviceIdSchema: Schema<DeviceId> = object({
  id: ['id', optional(string())],
  kind: ['kind', optional(string())],
});
