/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DevicesProtocolEnum
 */
export enum DevicesProtocolEnum {
  LWM2m = 'LWM2M',
  OMDADM = 'OMDADM',
  HTTP = 'HTTP',
}

/**
 * Schema for DevicesProtocolEnum
 */
export const devicesProtocolEnumSchema: Schema<DevicesProtocolEnum> = stringEnum(DevicesProtocolEnum);
