/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** A label for a single device. */
export interface DeviceLabels {
  /** The label you want to associate with the device. */
  name: string;
  /** The value of label */
  value: string;
}

export const deviceLabelsSchema: Schema<DeviceLabels> = object({
  name: ['name', string()],
  value: ['value', string()],
});
