/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { DeviceId, deviceIdSchema } from './deviceId';

/** Make changes to a device group, including changing the name and description, and adding or removing devices. */
export interface DeviceGroupUpdateRequest {
  /** Zero or more devices to add to the device group, specified by device ID. The devices will be removed from their current device groups. You can use POST /devices/actions/list to get a list of all devices in the account. */
  devicesToAdd?: DeviceId[];
  /** Zero or more devices to remove from the device group, specified by device ID. The devices will be added to the default device group. */
  devicesToRemove?: DeviceId[];
  /** A new description for the device group. Do not include this parameter to leave the group description unchanged. */
  newGroupDescription?: string;
  /** A new name for the device group. Do not include this parameter if you want to leave the group name unchanged. */
  newGroupName?: string;
}

export const deviceGroupUpdateRequestSchema: Schema<DeviceGroupUpdateRequest> = object(
  {
    devicesToAdd: ['devicesToAdd', optional(array(lazy(() => deviceIdSchema)))],
    devicesToRemove: [
      'devicesToRemove',
      optional(array(lazy(() => deviceIdSchema))),
    ],
    newGroupDescription: ['newGroupDescription', optional(string())],
    newGroupName: ['newGroupName', optional(string())],
  }
);
