/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Array of software upgrade objects with the specified status. */
export interface DeviceSoftwareUpgrade {
  /** Device identifier. */
  deviceId: string;
  /** Upgrade identifier. */
  id: string;
  /** Account identifier. */
  accountName: string;
  /** Software name. */
  softwareName?: string;
  /** Software upgrade start date. */
  startDate: string;
  /** Software upgrade status. */
  status: string;
  /** Software upgrade result reason. */
  reason: string;
}

export const deviceSoftwareUpgradeSchema: Schema<DeviceSoftwareUpgrade> = object(
  {
    deviceId: ['deviceId', string()],
    id: ['id', string()],
    accountName: ['accountName', string()],
    softwareName: ['softwareName', optional(string())],
    startDate: ['startDate', string()],
    status: ['status', string()],
    reason: ['reason', string()],
  }
);
