/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import {
  CallbackServiceNameEnum,
  callbackServiceNameEnumSchema,
} from './callbackServiceNameEnum';

export interface DeviceLocationCallback {
  /** The name of the callback service. */
  name: CallbackServiceNameEnum;
  /** The location of your callback listener. */
  url: string;
}

export const deviceLocationCallbackSchema: Schema<DeviceLocationCallback> = object(
  { name: ['name', callbackServiceNameEnumSchema], url: ['url', string()] }
);
