/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

/** Status of the diagnostic services subscription. */
export interface DiagnosticsSubscription {
  /** Account identifier in "##########-#####". An account name is usually numeric, and must include any leading zeros. */
  accountName: string;
  /** The date and time of when the subscription was created. */
  createdOn: string;
  /** The date and time of when the subscription was last updated. */
  lastUpdated: string;
  /** Number of licenses currently assigned to devices. */
  totalAllowed: number;
  /** Number of licenses currently used by the devices. */
  totalUsed: number;
  /** Name of the SKU for the account. */
  skuName: string;
}

export const diagnosticsSubscriptionSchema: Schema<DiagnosticsSubscription> = object(
  {
    accountName: ['accountName', string()],
    createdOn: ['createdOn', string()],
    lastUpdated: ['lastUpdated', string()],
    totalAllowed: ['totalAllowed', number()],
    totalUsed: ['totalUsed', number()],
    skuName: ['skuName', string()],
  }
);
