/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Error response attribute of a service. */
export interface EdgeServiceOnboardingResult {
  /** Code of the error. eg: SDMS_000_000. */
  code?: string;
  /** Brief description of the error in the form of a message. */
  message?: string;
  /** Suggestion on how to fix the issue. */
  remedyMessage?: string;
}

export const edgeServiceOnboardingResultSchema: Schema<EdgeServiceOnboardingResult> = object(
  {
    code: ['code', optional(string())],
    message: ['message', optional(string())],
    remedyMessage: ['remedyMessage', optional(string())],
  }
);
