/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EdgeServiceRepositoryTypeEnum
 */
export enum EdgeServiceRepositoryTypeEnum {
  Git = 'Git',
  Helm = 'Helm',
}

/**
 * Schema for EdgeServiceRepositoryTypeEnum
 */
export const edgeServiceRepositoryTypeEnumSchema: Schema<EdgeServiceRepositoryTypeEnum> = stringEnum(EdgeServiceRepositoryTypeEnum);
