/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface EdgeServiceLaunchParams {
  key?: string;
  value?: string;
}

export const edgeServiceLaunchParamsSchema: Schema<EdgeServiceLaunchParams> = object(
  { key: ['key', optional(string())], value: ['value', optional(string())] }
);
