/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  UEIdentityTypeEnum,
  uEIdentityTypeEnumSchema,
} from './uEIdentityTypeEnum';

export interface EdsDiscoveryIntent {
  /** UEIdentity to discover EDS location service. */
  ueIdentity?: string;
  /** Default type for ueIdentityType. */
  ueIdentityType?: UEIdentityTypeEnum;
}

export const edsDiscoveryIntentSchema: Schema<EdsDiscoveryIntent> = object({
  ueIdentity: ['ueIdentity', optional(string())],
  ueIdentityType: ['ueIdentityType', optional(uEIdentityTypeEnumSchema)],
});
