/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ESIMDeviceList, eSIMDeviceListSchema } from './eSIMDeviceList';

export interface ESIMProfileRequest {
  devices?: ESIMDeviceList[];
  carrierName?: string;
  accountName?: string;
  servicePlan?: string;
  mdnZipCode?: string;
}

export const eSIMProfileRequestSchema: Schema<ESIMProfileRequest> = object({
  devices: ['devices', optional(array(lazy(() => eSIMDeviceListSchema)))],
  carrierName: ['carrierName', optional(string())],
  accountName: ['accountName', optional(string())],
  servicePlan: ['servicePlan', optional(string())],
  mdnZipCode: ['mdnZipCode', optional(string())],
});
