/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Additional properties associated with data. */
export interface ExtendedAttributes {
  key?: string;
  value?: string;
}

export const extendedAttributesSchema: Schema<ExtendedAttributes> = object({
  key: ['key', optional(string())],
  value: ['value', optional(string())],
});
