/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** List of fields affected by the event. */
export interface Fields2 {
  temperature?: string;
}

export const fields2Schema: Schema<Fields2> = object({
  temperature: ['temperature', optional(string())],
});
