/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface FilterCriteriaAccountGroupShare {
  ratePlanGroupId?: number;
}

export const filterCriteriaAccountGroupShareSchema: Schema<FilterCriteriaAccountGroupShare> = object(
  { ratePlanGroupId: ['ratePlanGroupId', optional(number())] }
);
