/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  ReadySimServicePlan,
  readySimServicePlanSchema,
} from './readySimServicePlan';

export interface Filtercriteria {
  filterCriteria?: ReadySimServicePlan[];
}

export const filtercriteriaSchema: Schema<Filtercriteria> = object({
  filterCriteria: [
    'filterCriteria',
    optional(array(lazy(() => readySimServicePlanSchema))),
  ],
});
