/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FirmwareTypeListEnum
 */
export enum FirmwareTypeListEnum {
  Append = 'append',
  Remove = 'remove',
}

/**
 * Schema for FirmwareTypeListEnum
 */
export const firmwareTypeListEnumSchema: Schema<FirmwareTypeListEnum> = stringEnum(FirmwareTypeListEnum);
