/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

/** A list of IMEIs for devices to be synchronized between ThingSpace and the FOTA server. */
export interface FirmwareIMEI {
  /** Device IMEI list. */
  deviceList: string[];
}

export const firmwareIMEISchema: Schema<FirmwareIMEI> = object({
  deviceList: ['deviceList', array(string())],
});
