/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** A JSON object for each device that was included in the upgrade, showing the device IMEI, the status of the upgrade, and additional information about the status. */
export interface FirmwareUpgradeDeviceListItem {
  /** Device IMEI. */
  deviceId?: string;
  /** The status of the upgrade for this device. */
  status?: string;
  /** Additional details about the status. Not included when status='Request Pending.' */
  resultReason?: string;
}

export const firmwareUpgradeDeviceListItemSchema: Schema<FirmwareUpgradeDeviceListItem> = object(
  {
    deviceId: ['deviceId', optional(string())],
    status: ['status', optional(string())],
    resultReason: ['resultReason', optional(string())],
  }
);
