/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface FlowInfo {
  flowServer?: string;
  flowDevice?: string;
  flowDirection?: string;
  flowProtocol?: string;
  qciOption?: string;
}

export const flowInfoSchema: Schema<FlowInfo> = object({
  flowServer: ['flowServer', optional(string())],
  flowDevice: ['flowDevice', optional(string())],
  flowDirection: ['flowDirection', optional(string())],
  flowProtocol: ['flowProtocol', optional(string())],
  qciOption: ['qciOption', optional(string())],
});
