/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Callback URL where the listening service is running. */
export interface FotaV3CallbackRegistrationRequest {
  /** Callback URL for an subscribed service. */
  url?: string;
}

export const fotaV3CallbackRegistrationRequestSchema: Schema<FotaV3CallbackRegistrationRequest> = object(
  { url: ['url', optional(string())] }
);
