/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema';

/** Response to a successful request. */
export interface FotaV2SuccessResult {
  success: boolean;
}

export const fotaV2SuccessResultSchema: Schema<FotaV2SuccessResult> = object({
  success: ['success', boolean()],
});
