/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

/** A response to a successful request contains a single Boolean value. */
export interface FotaV1SuccessResult {
  /** True is returned in case of success. */
  success?: boolean;
}

export const fotaV1SuccessResultSchema: Schema<FotaV1SuccessResult> = object({
  success: ['success', optional(boolean())],
});
