/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface GetAccountDeviceConsent {
  /** An array of device identifiers */
  deviceList?: unknown[];
  /** The numeric name of the account, including leading zeros. */
  accountName?: string;
  /** If consent is set at the account level, this value will show the consent level. */
  allDeviceConsent?: number;
}

export const getAccountDeviceConsentSchema: Schema<GetAccountDeviceConsent> = object(
  {
    deviceList: ['deviceList', optional(array(unknown()))],
    accountName: ['accountName', optional(string())],
    allDeviceConsent: ['allDeviceConsent', optional(number())],
  }
);
