/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { DeviceIdentifier, deviceIdentifierSchema } from './deviceIdentifier';

/** Get device experience score history. */
export interface GetDeviceExperienceScoreHistoryRequest {
  /** Account name. */
  accountName: string;
  /** Device Id details. */
  deviceId: DeviceIdentifier;
}

export const getDeviceExperienceScoreHistoryRequestSchema: Schema<GetDeviceExperienceScoreHistoryRequest> = object(
  {
    accountName: ['accountName', string()],
    deviceId: ['deviceId', lazy(() => deviceIdentifierSchema)],
  }
);
