/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** MEC Performance Consent Response */
export interface GetMECPerformanceConsentResponse {
  /** MEC Performance Consent Response. */
  consent?: string;
}

export const getMECPerformanceConsentResponseSchema: Schema<GetMECPerformanceConsentResponse> = object(
  { consent: ['consent', optional(string())] }
);
