/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface GetTriggerResponse {
  accountName?: string;
  comparator?: string;
  createdAt?: string;
  groupName?: string;
  modifiedAt?: string;
  notificationGroupName?: string;
  organizationName?: string;
  smsType?: string;
  threshold?: string;
  thresholdUnit?: string;
  triggerCategory?: string;
  triggerCycle?: string;
  triggerId?: string;
  triggerName?: string;
}

export const getTriggerResponseSchema: Schema<GetTriggerResponse> = object({
  accountName: ['accountName', optional(string())],
  comparator: ['comparator', optional(string())],
  createdAt: ['createdAt', optional(string())],
  groupName: ['groupName', optional(string())],
  modifiedAt: ['modifiedAt', optional(string())],
  notificationGroupName: ['notificationGroupName', optional(string())],
  organizationName: ['organizationName', optional(string())],
  smsType: ['smsType', optional(string())],
  threshold: ['threshold', optional(string())],
  thresholdUnit: ['thresholdUnit', optional(string())],
  triggerCategory: ['triggerCategory', optional(string())],
  triggerCycle: ['triggerCycle', optional(string())],
  triggerId: ['triggerId', optional(string())],
  triggerName: ['triggerName', optional(string())],
});
