/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { GIODeviceId, gIODeviceIdSchema } from './gIODeviceId';
import { KvPair, kvPairSchema } from './kvPair';

export interface GIOSMSSendRequest {
  accountName?: string;
  customFields?: KvPair[];
  dataEncoding?: string;
  groupName?: string;
  servicePlan?: string;
  timeToLive?: string;
  deviceIds: GIODeviceId[];
  smsMessage: string;
}

export const gIOSMSSendRequestSchema: Schema<GIOSMSSendRequest> = object({
  accountName: ['accountName', optional(string())],
  customFields: ['customFields', optional(array(lazy(() => kvPairSchema)))],
  dataEncoding: ['dataEncoding', optional(string())],
  groupName: ['groupName', optional(string())],
  servicePlan: ['servicePlan', optional(string())],
  timeToLive: ['timeToLive', optional(string())],
  deviceIds: ['deviceIds', array(lazy(() => gIODeviceIdSchema))],
  smsMessage: ['smsMessage', string()],
});
