/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for HookTypeEnum
 */
export enum HookTypeEnum {
  PREINSTALLATION = 'PRE_INSTALLATION',
  POSTINSTALLATION = 'POST_INSTALLATION',
}

/**
 * Schema for HookTypeEnum
 */
export const hookTypeEnumSchema: Schema<HookTypeEnum> = stringEnum(HookTypeEnum);
