/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Callback registration request. */
export interface HyperPreciseLocationCallback {
  /** The name of the callback service that you want to subscribe to. */
  name: string;
  /** The address on your server where you have enabled a listening service for the specific type of callback messages. Specify a URL that is reachable from the Verizon data centers. If your service is running on HTTPS, you should use a one-way authentication certificate with a white-listed IP address. */
  url: string;
}

export const hyperPreciseLocationCallbackSchema: Schema<HyperPreciseLocationCallback> = object(
  { name: ['name', string()], url: ['url', string()] }
);
