/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  ErrorResponseCodeEnum,
  errorResponseCodeEnumSchema,
} from './errorResponseCodeEnum';
import {
  HttpStatusCodeEnum,
  httpStatusCodeEnumSchema,
} from './httpStatusCodeEnum';

/** Error message. */
export interface IErrorMessage {
  /** Error Code. */
  errorCode?: ErrorResponseCodeEnum;
  /** Details and additional information about the error code. */
  errorMessage?: string;
  /** HTML error code and description. */
  httpStatusCode?: HttpStatusCodeEnum;
  /** More detail and information about the HTML error code. */
  detailErrorMessage?: string;
}

export const iErrorMessageSchema: Schema<IErrorMessage> = object({
  errorCode: ['errorCode', optional(errorResponseCodeEnumSchema)],
  errorMessage: ['errorMessage', optional(string())],
  httpStatusCode: ['httpStatusCode', optional(httpStatusCodeEnumSchema)],
  detailErrorMessage: ['detailErrorMessage', optional(string())],
});
