/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Success response. */
export interface IntelligenceSuccessResult {
  /** Anomaly detection status. */
  status?: string;
}

export const intelligenceSuccessResultSchema: Schema<IntelligenceSuccessResult> = object(
  { status: ['status', optional(string())] }
);
