/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface KeysmsPercentage50 {
  key?: string;
  value?: boolean;
}

export const keysmsPercentage50Schema: Schema<KeysmsPercentage50> = object({
  key: ['key', optional(string())],
  value: ['value', optional(boolean())],
});
