/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Label {
  name?: string;
  value?: string;
}

export const labelSchema: Schema<Label> = object({
  name: ['name', optional(string())],
  value: ['value', optional(string())],
});
