/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface LinkedServiceInstance {
  id?: string;
}

export const linkedServiceInstanceSchema: Schema<LinkedServiceInstance> = object(
  { id: ['id', optional(string())] }
);
