/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

/** Response on successful retrieval of service profiles. */
export interface ListServiceProfilesResult {
  /** HTTP status code. */
  status?: string;
  /** A comma delimited list of all the service profiles registered under your API key. */
  data?: string[];
}

export const listServiceProfilesResultSchema: Schema<ListServiceProfilesResult> = object(
  {
    status: ['status', optional(string())],
    data: ['data', optional(array(string()))],
  }
);
