/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  MECPlatformResource,
  mECPlatformResourceSchema,
} from './mECPlatformResource';

/** Response to return the optimal 5G Edge platforms for deployment based on a region, service profile of the service that you want to deploy or user equipment. */
export interface ListMECPlatformsResult {
  /** A list of optimal MEC Platforms where you can register your deployed application. */
  mECPlatforms?: MECPlatformResource[];
}

export const listMECPlatformsResultSchema: Schema<ListMECPlatformsResult> = object(
  {
    mECPlatforms: [
      'MECPlatforms',
      optional(array(lazy(() => mECPlatformResourceSchema))),
    ],
  }
);
