/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Region, regionSchema } from './region';

/** Response to return an array of all regions in the Verizon 5G Edge service. You can use the region IDs from the response to find optimal Edge platforms or service endpoints. */
export interface ListRegionsResult {
  /** An array of all regions in the Verizon 5G Edge service. */
  regions?: Region[];
}

export const listRegionsResultSchema: Schema<ListRegionsResult> = object({
  regions: ['regions', optional(array(lazy(() => regionSchema)))],
});
