/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { ReportStatusEnum, reportStatusEnumSchema } from './reportStatusEnum';

/** Status of the report. */
export interface LocationReportStatus {
  /** The transaction ID of the report. */
  txid?: string;
  /** Status of the report. */
  status?: ReportStatusEnum;
}

export const locationReportStatusSchema: Schema<LocationReportStatus> = object({
  txid: ['txid', optional(string())],
  status: ['status', optional(reportStatusEnumSchema)],
});
