/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Coordinates, coordinatesSchema } from './coordinates';

/** Location coordinates. */
export interface Locationscoord {
  coordinatesList: Coordinates[];
}

export const locationscoordSchema: Schema<Locationscoord> = object({
  coordinatesList: ['coordinatesList', array(lazy(() => coordinatesSchema))],
});
