/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Request to initiate a Connectivity Management session and returns a VZ-M2M session token that is required in subsequent API requests. */
export interface LogInRequest {
  /** The username for authentication. */
  username?: string;
  /** The password for authentication. */
  password?: string;
}

export const logInRequestSchema: Schema<LogInRequest> = object({
  username: ['username', optional(string())],
  password: ['password', optional(string())],
});
