/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Response to initiate a Connectivity Management session and returns a VZ-M2M session token that is required in subsequent API requests. */
export interface LogInResult {
  /** The identifier for the session that was created by the request. Store the sessionToken for use in the header of all other API requests. */
  sessionToken?: string;
}

export const logInResultSchema: Schema<LogInResult> = object({
  sessionToken: ['sessionToken', optional(string())],
});
