/**
 * Verizon ThingSpace Quality of Service API endpointsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface M201success {
  requestId?: string;
}

export const m201successSchema: Schema<M201success> = object({
  requestId: ['requestId', optional(string())],
});
