/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface M5gBiRequestResponse {
  requestId?: string;
}

export const m5gBiRequestResponseSchema: Schema<M5gBiRequestResponse> = object({
  requestId: ['requestId', optional(string())],
});
