/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, optional, Schema } from '../schema';
import {
  M5gBiaccountNameobject,
  m5gBiaccountNameobjectSchema,
} from './m5gBiaccountNameobject';

export interface M5gBideviceDetailsresponse {
  hasMoreData?: boolean;
  devices?: M5gBiaccountNameobject[];
}

export const m5gBideviceDetailsresponseSchema: Schema<M5gBideviceDetailsresponse> = object(
  {
    hasMoreData: ['hasMoreData', optional(boolean())],
    devices: [
      'devices',
      optional(array(lazy(() => m5gBiaccountNameobjectSchema))),
    ],
  }
);
