/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { M5gBiAddress, m5gBiAddressSchema } from './m5gBiAddress';
import {
  M5gBiCustomerName,
  m5gBiCustomerNameSchema,
} from './m5gBiCustomerName';

export interface M5gBiprimaryPlaceofuse {
  address?: M5gBiAddress;
  customerName?: M5gBiCustomerName;
}

export const m5gBiprimaryPlaceofuseSchema: Schema<M5gBiprimaryPlaceofuse> = object(
  {
    address: ['address', optional(lazy(() => m5gBiAddressSchema))],
    customerName: [
      'customerName',
      optional(lazy(() => m5gBiCustomerNameSchema)),
    ],
  }
);
