/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface M5gBiattribute2 {
  key?: string;
  value?: string;
}

export const m5gBiattribute2Schema: Schema<M5gBiattribute2> = object({
  key: ['key', optional(string())],
  value: ['value', optional(string())],
});
