/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';
import { ServiceNameEnum, serviceNameEnumSchema } from './serviceNameEnum';

export interface ManagedAccountsAddRequest {
  /** Account identifier */
  accountName: string;
  /** Service name */
  serviceName: ServiceNameEnum;
  /** SKU name */
  type: string;
  /** managed account list */
  managedAccList: string[];
}

export const managedAccountsAddRequestSchema: Schema<ManagedAccountsAddRequest> = object(
  {
    accountName: ['accountName', string()],
    serviceName: ['serviceName', serviceNameEnumSchema],
    type: ['type', string()],
    managedAccList: ['managedAccList', array(string())],
  }
);
