/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { ServiceNameEnum, serviceNameEnumSchema } from './serviceNameEnum';

export interface ManagedAccountCancelResponse {
  /** Transaction identifier */
  txid: string;
  /** Managed account identifier */
  accountName: string;
  /** Primary account identifier */
  paccountName: string;
  /** Service name */
  serviceName: ServiceNameEnum;
  /** Deactivate/cancel status, Success or Fail */
  status: string;
  /** Detailed reason */
  reason: string;
}

export const managedAccountCancelResponseSchema: Schema<ManagedAccountCancelResponse> = object(
  {
    txid: ['txid', string()],
    accountName: ['accountName', string()],
    paccountName: ['paccountName', string()],
    serviceName: ['serviceName', serviceNameEnumSchema],
    status: ['status', string()],
    reason: ['reason', string()],
  }
);
