/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** List of the field names and values to set. */
export interface MConfiguration {
  frequency?: string;
}

export const mConfigurationSchema: Schema<MConfiguration> = object({
  frequency: ['frequency', optional(string())],
});
