/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface MECDeviceId {
  id: string;
  kind: string;
}

export const mECDeviceIdSchema: Schema<MECDeviceId> = object({
  id: ['id', string()],
  kind: ['kind', string()],
});
