/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, nullable, object, optional, Schema, string } from '../schema';

/** Result of the query for obtaining MEC performance metrics. */
export interface MECPerformanceQueryResult {
  /** Name of the parameter. */
  name?: string;
  /** Parameter values. */
  data?: (string | null)[];
}

export const mECPerformanceQueryResultSchema: Schema<MECPerformanceQueryResult> = object(
  {
    name: ['name', optional(string())],
    data: ['data', optional(array(nullable(string())))],
  }
);
