/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { AccountDeviceList, accountDeviceListSchema } from './accountDeviceList';
import { CustomFields, customFieldsSchema } from './customFields';
import { DeviceFilter, deviceFilterSchema } from './deviceFilter';

/** Request to move active devices from one billing account to another within a customer profile. */
export interface MoveDeviceRequest {
  /** The name of the billing account that you want to move the devices to. */
  accountName?: string;
  /** Specify the kind of the device identifier, the type of match, and the string that you want to match. */
  filter?: DeviceFilter;
  /** Custom field names and values, if you want to only include devices that have matching values. */
  customFields?: CustomFields[];
  /** Up to 10,000 devices that you want to move to a different account, specified by device identifier. */
  devices?: AccountDeviceList[];
  /** The name of a device group, to only include devices in that group. */
  groupName?: string;
  /** The pool from which device IP addresses will be derived in the new account. If you do not include this element, the default pool will be used. */
  carrierIpPoolName?: string;
  /** The service plan code that you want to assign to the devices in the new account. If you do not include this element, ThingSpace will attempt to use the current service plan, which will result in a error if the new account does not have that service plan. */
  servicePlan?: string;
}

export const moveDeviceRequestSchema: Schema<MoveDeviceRequest> = object({
  accountName: ['accountName', optional(string())],
  filter: ['filter', optional(lazy(() => deviceFilterSchema))],
  customFields: [
    'customFields',
    optional(array(lazy(() => customFieldsSchema))),
  ],
  devices: ['devices', optional(array(lazy(() => accountDeviceListSchema)))],
  groupName: ['groupName', optional(string())],
  carrierIpPoolName: ['carrierIpPoolName', optional(string())],
  servicePlan: ['servicePlan', optional(string())],
});
