/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface NamespaceIdItem {
  id?: string;
  /** User display name. */
  name?: string;
}

export const namespaceIdItemSchema: Schema<NamespaceIdItem> = object({
  id: ['id', optional(string())],
  name: ['name', optional(string())],
});
