/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface NodeGroupItemTag {
  associateCarrierIp?: string;
}

export const nodeGroupItemTagSchema: Schema<NodeGroupItemTag> = object({
  associateCarrierIp: ['associate-carrier-ip', optional(string())],
});
