/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface NoOfDaysB4PromoExp {
  key?: string;
  value?: number;
}

export const noOfDaysB4PromoExpSchema: Schema<NoOfDaysB4PromoExp> = object({
  key: ['key', optional(string())],
  value: ['value', optional(number())],
});
