/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { DeviceId, deviceIdSchema } from './deviceId';

export interface NotificationReportStatusRequest {
  /** The name of a billing account. */
  accountName: string;
  /** An identifier for a single device. */
  device: DeviceId;
  /** The type of request. */
  requestType: string;
  /** The time at which the request expires. */
  requestExpirationTime?: string;
}

export const notificationReportStatusRequestSchema: Schema<NotificationReportStatusRequest> = object(
  {
    accountName: ['accountName', string()],
    device: ['device', lazy(() => deviceIdSchema)],
    requestType: ['requestType', string()],
    requestExpirationTime: ['requestExpirationTime', optional(string())],
  }
);
