/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import {
  NumericalDataUnitEnum,
  numericalDataUnitEnumSchema,
} from './numericalDataUnitEnum';

/** Describes value and unit of time. */
export interface NumericalData {
  /** Numerical value. */
  value?: number;
  /** Unit of time. */
  unit?: NumericalDataUnitEnum;
}

export const numericalDataSchema: Schema<NumericalData> = object({
  value: ['value', optional(number())],
  unit: ['unit', optional(numericalDataUnitEnumSchema)],
});
