/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { IntentChainItem, intentChainItemSchema } from './intentChainItem';

export interface PlacementIntents {
  isPlacementAtLaunchEnabled?: boolean;
  groupId?: string;
  intentChain?: IntentChainItem[];
}

export const placementIntentsSchema: Schema<PlacementIntents> = object({
  isPlacementAtLaunchEnabled: [
    'isPlacementAtLaunchEnabled',
    optional(boolean()),
  ],
  groupId: ['groupId', optional(string())],
  intentChain: [
    'intentChain',
    optional(array(lazy(() => intentChainItemSchema))),
  ],
});
