/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Position error. */
export interface PositionError {
  /** Time location obtained. */
  time?: string;
  /** UTC offset of time. */
  utcoffset?: string;
  /** Error type returned from location server. */
  type?: string;
  /** Additional information about the error. */
  info?: string;
}

export const positionErrorSchema: Schema<PositionError> = object({
  time: ['time', optional(string())],
  utcoffset: ['utcoffset', optional(string())],
  type: ['type', optional(string())],
  info: ['info', optional(string())],
});
