/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

/** Position data. */
export interface PositionData {
  /** Time location obtained. */
  time?: string;
  /** UTC offset of time. */
  utcoffset?: string;
  /** X coordinate of location. */
  x?: string;
  /** Y coordinate of location. */
  y?: string;
  /** Radius of the location in meters. */
  radius?: string;
  /** Whether requested accurary is met or not. */
  qos?: boolean;
}

export const positionDataSchema: Schema<PositionData> = object({
  time: ['time', optional(string())],
  utcoffset: ['utcoffset', optional(string())],
  x: ['x', optional(string())],
  y: ['y', optional(string())],
  radius: ['radius', optional(string())],
  qos: ['qos', optional(boolean())],
});
