/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { DeviceList, deviceListSchema } from './deviceList';

export interface ProfileChangeStateRequest {
  devices?: DeviceList[];
  accountName?: string;
  smsrOid?: string;
}

export const profileChangeStateRequestSchema: Schema<ProfileChangeStateRequest> = object(
  {
    devices: ['devices', optional(array(lazy(() => deviceListSchema)))],
    accountName: ['accountName', optional(string())],
    smsrOid: ['smsrOid', optional(string())],
  }
);
