/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ProfileStatusFilterEnum
 */
export enum ProfileStatusFilterEnum {
  ENABLE = 'ENABLE',
  DISABLE = 'DISABLE',
  DOWNLOADDISABLE = 'DOWNLOAD_DISABLE',
  DOWNLOADENABLE = 'DOWNLOAD_ENABLE',
  NOTDOWNLOADED = 'NOT_DOWNLOADED',
  UNKNOWN = 'UNKNOWN',
  DELETE = 'DELETE',
}

/**
 * Schema for ProfileStatusFilterEnum
 */
export const profileStatusFilterEnumSchema: Schema<ProfileStatusFilterEnum> = stringEnum(
  ProfileStatusFilterEnum
);
