/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { DeviceList, deviceListSchema } from './deviceList';
import { PrimaryPlaceOfUse, primaryPlaceOfUseSchema } from './primaryPlaceOfUse';

export interface ProfileRequest {
  devices?: DeviceList[];
  carrierName?: string;
  accountName?: string;
  servicePlan?: string;
  mdnZipCode?: string;
  primaryPlaceOfUse?: PrimaryPlaceOfUse[];
}

export const profileRequestSchema: Schema<ProfileRequest> = object({
  devices: ['devices', optional(array(lazy(() => deviceListSchema)))],
  carrierName: ['carrierName', optional(string())],
  accountName: ['accountName', optional(string())],
  servicePlan: ['servicePlan', optional(string())],
  mdnZipCode: ['mdnZipCode', optional(string())],
  primaryPlaceOfUse: [
    'primaryPlaceOfUse',
    optional(array(lazy(() => primaryPlaceOfUseSchema))),
  ],
});
