/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ProjectItem {
  projectId?: string;
  clusterId?: string;
  id?: string;
  createdAt?: string;
  modifiedAt?: string;
}

export const projectItemSchema: Schema<ProjectItem> = object({
  projectId: ['project_id', optional(string())],
  clusterId: ['cluster_id', optional(string())],
  id: ['id', optional(string())],
  createdAt: ['created_at', optional(string())],
  modifiedAt: ['modified_at', optional(string())],
});
