/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, optional, Schema } from '../schema';
import { Keyschunk2, keyschunk2Schema } from './keyschunk2';
import {
  ReadySimServicePlan,
  readySimServicePlanSchema,
} from './readySimServicePlan';

export interface PromoAlert {
  filterCriteria?: ReadySimServicePlan[];
  condition?: Keyschunk2[];
  enablePromoExp?: boolean;
}

export const promoAlertSchema: Schema<PromoAlert> = object({
  filterCriteria: [
    'filterCriteria',
    optional(array(lazy(() => readySimServicePlanSchema))),
  ],
  condition: ['condition', optional(array(lazy(() => keyschunk2Schema)))],
  enablePromoExp: ['enablePromoExp', optional(boolean())],
});
