/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Kind1Enum, kind1EnumSchema } from './kind1Enum';

export interface PropertyDeviceId {
  id?: string;
  kind?: Kind1Enum;
}

export const propertyDeviceIdSchema: Schema<PropertyDeviceId> = object({
  id: ['id', optional(string())],
  kind: ['kind', optional(kind1EnumSchema)],
});
