/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { GIODeviceId, gIODeviceIdSchema } from './gIODeviceId';

export interface ProvhistoryRequest {
  accountName?: string;
  deviceFilter?: GIODeviceId[];
  earliest?: string;
  latest?: string;
}

export const provhistoryRequestSchema: Schema<ProvhistoryRequest> = object({
  accountName: ['accountName', optional(string())],
  deviceFilter: [
    'deviceFilter',
    optional(array(lazy(() => gIODeviceIdSchema))),
  ],
  earliest: ['earliest', optional(string())],
  latest: ['latest', optional(string())],
});
