/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ProvisioningStatusFilterEnum
 */
export enum ProvisioningStatusFilterEnum {
  UNKNOWN = 'UNKNOWN',
  DEACTIVATED = 'DEACTIVATED',
  ACTIVATED = 'ACTIVATED',
  DEACTIVE = 'DEACTIVE',
  ACTIVE = 'ACTIVE',
  SUSPEND = 'SUSPEND',
  PENDINGACTIVATION = 'PENDING_ACTIVATION',
  PENDINGDEACTIVATION = 'PENDING_DEACTIVATION',
  PREACTIVE = 'PRE_ACTIVE',
  ACTIVATIONREADY = 'ACTIVATION_READY',
  INVENTORY = 'INVENTORY',
  PURGED = 'PURGED',
  REPLACED = 'REPLACED',
  RETIRED = 'RETIRED',
  TESTREADY = 'TEST_READY',
}

/**
 * Schema for ProvisioningStatusFilterEnum
 */
export const provisioningStatusFilterEnumSchema: Schema<ProvisioningStatusFilterEnum> = stringEnum(
  ProvisioningStatusFilterEnum
);
