/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Provision {
  edgeId?: string;
  provisionId?: string;
  createdAt?: string;
  modifiedAt?: string;
  organizationId?: string;
  partnerId?: string;
  type?: string;
  runningState?: string;
  runningStatus?: string;
  id?: string;
  status?: string;
  comments?: string;
  nodegroupId?: string;
}

export const provisionSchema: Schema<Provision> = object({
  edgeId: ['edge_id', optional(string())],
  provisionId: ['provision_id', optional(string())],
  createdAt: ['created_at', optional(string())],
  modifiedAt: ['modified_at', optional(string())],
  organizationId: ['organization_id', optional(string())],
  partnerId: ['partner_id', optional(string())],
  type: ['type', optional(string())],
  runningState: ['running_state', optional(string())],
  runningStatus: ['running_status', optional(string())],
  id: ['id', optional(string())],
  status: ['status', optional(string())],
  comments: ['comments', optional(string())],
  nodegroupId: ['nodegroup_id', optional(string())],
});
