/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface PWNProfile {
  profileId?: string;
  profileName?: string;
}

export const pWNProfileSchema: Schema<PWNProfile> = object({
  profileId: ['profileId', optional(string())],
  profileName: ['profileName', optional(string())],
});
