/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface QosDeviceId {
  id?: string;
  kind?: string;
}

export const qosDeviceIdSchema: Schema<QosDeviceId> = object({
  id: ['id', optional(string())],
  kind: ['kind', optional(string())],
});
