/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { FlowInfo, flowInfoSchema } from './flowInfo';
import { QosDeviceId, qosDeviceIdSchema } from './qosDeviceId';

export interface QosDeviceInfo {
  deviceId: QosDeviceId;
  deviceIPv6Addr?: string;
  flowInfo: FlowInfo[];
}

export const qosDeviceInfoSchema: Schema<QosDeviceInfo> = object({
  deviceId: ['deviceId', lazy(() => qosDeviceIdSchema)],
  deviceIPv6Addr: ['deviceIPv6Addr', optional(string())],
  flowInfo: ['flowInfo', array(lazy(() => flowInfoSchema))],
});
