/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Response to register Service Endpoints of a deployed application to specified Muli-access Edge Compute (MEC) Platforms. */
export interface RegisterServiceEndpointResult {
  /** A system-defined string identifier representing one or more registered Service Endpoints. */
  serviceEndpointsId?: string;
}

export const registerServiceEndpointResultSchema: Schema<RegisterServiceEndpointResult> = object(
  { serviceEndpointsId: ['serviceEndpointsId', optional(string())] }
);
