/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

/** Information representing a certain geographical or logical area where MEC resources and services are provided. */
export interface Region {
  /** The unique identifier of the region. */
  regionId?: string | null;
  /** A relevant and identifiable region name. */
  name?: string | null;
  /** A two-character alpha code for a country, based on ISO 3166-1 alpha-2. This is future functionality, so the value returned is 'null'. */
  countryCode?: string | null;
  /** The metropolitan area or 'City' value.  This is future functionality, so the value returned is 'null'. */
  metro?: string | null;
  /** This is a sub-set of 'City' and is similar to 'Zone'. This is future functionality, so the value returned is 'null'. */
  area?: string | null;
}

export const regionSchema: Schema<Region> = object({
  regionId: ['regionId', optional(nullable(string()))],
  name: ['name', optional(nullable(string()))],
  countryCode: ['countryCode', optional(nullable(string()))],
  metro: ['metro', optional(nullable(string()))],
  area: ['area', optional(nullable(string()))],
});
