/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Credentials of a repository. */
export interface RepositoryCredential {
  /** User name to connect to the repository. */
  name?: string;
  /** Account password to connect to user provided repository. */
  password?: string;
}

export const repositoryCredentialSchema: Schema<RepositoryCredential> = object({
  name: ['name', optional(string())],
  password: ['password', optional(string())],
});
