/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RepositoryTypeEnum
 */
export enum RepositoryTypeEnum {
  GIT = 'GIT',
  HELM = 'HELM',
}

/**
 * Schema for RepositoryTypeEnum
 */
export const repositoryTypeEnumSchema: Schema<RepositoryTypeEnum> = stringEnum(RepositoryTypeEnum);
