/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReportStatusEnum
 */
export enum ReportStatusEnum {
  QUEUED = 'QUEUED',
  INPROGRESS = 'INPROGRESS',
  COMPLETED = 'COMPLETED',
}

/**
 * Schema for ReportStatusEnum
 */
export const reportStatusEnumSchema: Schema<ReportStatusEnum> = stringEnum(ReportStatusEnum);
