/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  ResourcesServiceEndpoint,
  resourcesServiceEndpointSchema,
} from './resourcesServiceEndpoint';

/** Edge hosted service represented by Service Endpoint definition. */
export interface ResourcesEdgeHostedService {
  /** Edge Resource Name. A string identifier for a set of edge resources. */
  ern?: string;
  /** Service Endpoint path, address, and port. */
  serviceEndpoint?: ResourcesServiceEndpoint;
  /** Unique ID representing the Edge Application Provider. */
  applicationServerProviderId?: string;
  /** Unique ID representing the Edge Application. */
  applicationId?: string;
  serviceDescription?: string;
}

export const resourcesEdgeHostedServiceSchema: Schema<ResourcesEdgeHostedService> = object(
  {
    ern: ['ern', optional(string())],
    serviceEndpoint: [
      'serviceEndpoint',
      optional(lazy(() => resourcesServiceEndpointSchema)),
    ],
    applicationServerProviderId: [
      'applicationServerProviderId',
      optional(string()),
    ],
    applicationId: ['applicationId', optional(string())],
    serviceDescription: ['serviceDescription', optional(string())],
  }
);
