/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface RetrievesAvailableFilesResponse {
  /** ThingSpace-generated name of the file. You will use this name when listing or scheduling campaigns for the file. */
  fileName?: string;
  /** Version of the file. */
  fileVersion?: string;
  /** Software release note. */
  releaseNote?: string;
  /** The software-applicable device make. */
  make?: string;
  /** The software-applicable device model. */
  model?: string;
  /** Local target path on the device. */
  localTargetPath?: string;
  /** Valid values */
  distributionType?: string;
  /** The platform (Android, iOS, etc.,) that the software can be applied to. */
  devicePlatformId?: string;
}

export const retrievesAvailableFilesResponseSchema: Schema<RetrievesAvailableFilesResponse> = object(
  {
    fileName: ['fileName', optional(string())],
    fileVersion: ['fileVersion', optional(string())],
    releaseNote: ['releaseNote', optional(string())],
    make: ['make', optional(string())],
    model: ['model', optional(string())],
    localTargetPath: ['localTargetPath', optional(string())],
    distributionType: ['distributionType', optional(string())],
    devicePlatformId: ['devicePlatformId', optional(string())],
  }
);
