/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SandBoxStatusEnum
 */
export enum SandBoxStatusEnum {
  NA = 'NA',
  INPROGRESS = 'INPROGRESS',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

/**
 * Schema for SandBoxStatusEnum
 */
export const sandBoxStatusEnumSchema: Schema<SandBoxStatusEnum> = stringEnum(SandBoxStatusEnum);
