/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SandBoxStateEnum
 */
export enum SandBoxStateEnum {
  NOTSTARTED = 'NOT_STARTED',
  STARTED = 'STARTED',
  STOPPED = 'STOPPED',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  DELETED = 'DELETED',
  STOPINPROGRESS = 'STOP_IN_PROGRESS',
  PAUSEINPROGRESS = 'PAUSE_IN_PROGRESS',
  TESTINPROGRESS = 'TEST_IN_PROGRESS',
  MARKFORDELETION = 'MARK_FOR_DELETION',
}

/**
 * Schema for SandBoxStateEnum
 */
export const sandBoxStateEnumSchema: Schema<SandBoxStateEnum> = stringEnum(SandBoxStateEnum);
