/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Acceleration, accelerationSchema } from './acceleration';
import {
  DevicePropertylocation,
  devicePropertylocationSchema,
} from './devicePropertylocation';

/** List of device sensors and their most recently reported values. */
export interface SearchDeviceByPropertyFields {
  acceleration?: Acceleration;
  battery?: string;
  humidity?: string;
  light?: string;
  pressure?: string;
  signalStrength?: string;
  temperature?: string;
  devicePropertylocation?: DevicePropertylocation;
}

export const searchDeviceByPropertyFieldsSchema: Schema<SearchDeviceByPropertyFields> = object(
  {
    acceleration: ['acceleration', optional(lazy(() => accelerationSchema))],
    battery: ['battery', optional(string())],
    humidity: ['humidity', optional(string())],
    light: ['light', optional(string())],
    pressure: ['pressure', optional(string())],
    signalStrength: ['signalStrength', optional(string())],
    temperature: ['temperature', optional(string())],
    devicePropertylocation: [
      'DevicePropertylocation',
      optional(lazy(() => devicePropertylocationSchema)),
    ],
  }
);
