/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Success response. */
export interface SecuritySuccessResult {
  /** A unique string that associates the request with the results that are sent via a callback message.The ThingSpace Platform sends a separate callback message for each device that matches the request criteria, indicating whether the operation succeeded for that device and containing any requested information. All callback messages will have the same requestId. */
  requestId?: string;
}

export const securitySuccessResultSchema: Schema<SecuritySuccessResult> = object(
  { requestId: ['requestId', optional(string())] }
);
