/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Request for a subscription. */
export interface SecuritySubscriptionRequest {
  /** The name of a billing account. */
  accountName?: string;
  /** The Stock Keeping Unit (SKU). Valid skuNumbers for SIM-Secure for IoT are:SIMSec-IoT-Lt”. (Lifetime) Once a license is assigned to a SIM, the SIM-Secure feature is enabled for the life of the SIM.“TS-BUNDLE-KTO-SIMSEC-MRC”. (Bundle) The SIM-Secure Flex license can be assigned to or removed from a SIM at any time. This SKU is bundled with other ThingSpace Services.*“SIMSec-IoT”. (Flex) The SIM-Secure Flex license can be assigned to or removed from a SIM at any time. This SKU is purchased a la carte. */
  skuNumber?: string;
}

export const securitySubscriptionRequestSchema: Schema<SecuritySubscriptionRequest> = object(
  {
    accountName: ['accountName', optional(string())],
    skuNumber: ['skuNumber', optional(string())],
  }
);
