/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { ServiceStateEnum, serviceStateEnumSchema } from './serviceStateEnum';

/** Service which is selected. */
export interface SelectedService {
  /** Name of the service needs to be deployed. */
  name?: string;
  /** Name of the service user is created. */
  version?: string;
  /** Can have any value as - DRAFT, DESIGN, TESTING, PUBLISH, CERTIFY, READY_TO_USE, DEPRECATE, DELETED. */
  state?: ServiceStateEnum;
}

export const selectedServiceSchema: Schema<SelectedService> = object({
  name: ['name', optional(string())],
  version: ['version', optional(string())],
  state: ['state', optional(serviceStateEnumSchema)],
});
