/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';
import {
  ServiceDependencyPackageTypeEnum,
  serviceDependencyPackageTypeEnumSchema,
} from './serviceDependencyPackageTypeEnum';
import { ServiceTypeEnum, serviceTypeEnumSchema } from './serviceTypeEnum';

/** Dependency of the service. */
export interface ServiceDependency {
  /** The dependency rank. */
  rank?: number;
  /** Service Type e.g. Installation, Operations, Custom. */
  type?: ServiceTypeEnum;
  /** Name of the dependent service. */
  serviceName?: string;
  /** Version of the service being used. */
  version?: string;
  /** Deployment package type. */
  packageType?: ServiceDependencyPackageTypeEnum | null;
}

export const serviceDependencySchema: Schema<ServiceDependency> = object({
  rank: ['rank', optional(number())],
  type: ['type', optional(serviceTypeEnumSchema)],
  serviceName: ['serviceName', optional(string())],
  version: ['version', optional(string())],
  packageType: [
    'packageType',
    optional(nullable(serviceDependencyPackageTypeEnumSchema)),
  ],
});
