/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ServiceOnboardingTerraformGitTag {
  tagName: string;
  terraformPath: string;
}

export const serviceOnboardingTerraformGitTagSchema: Schema<ServiceOnboardingTerraformGitTag> = object(
  { tagName: ['tagName', string()], terraformPath: ['terraformPath', string()] }
);
