/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface ServiceOnboardingHelmGitTag {
  /** The user can provide tagName for the Helm chart. */
  tagName: string;
  /** The user can provide the path to the Helm chart. */
  helmChartPath: string;
  /** The user can provide an array of values.YAML files paths. */
  valuesYamlPaths?: string[];
}

export const serviceOnboardingHelmGitTagSchema: Schema<ServiceOnboardingHelmGitTag> = object(
  {
    tagName: ['tagName', string()],
    helmChartPath: ['helmChartPath', string()],
    valuesYamlPaths: ['valuesYamlPaths', optional(array(string()))],
  }
);
