/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ServiceUsage {
  /** Account identifier. */
  accountName?: string;
  /** Total requests for the account during the reporting period. */
  transactionsCount?: string;
}

export const serviceUsageSchema: Schema<ServiceUsage> = object({
  accountName: ['accountName', optional(string())],
  transactionsCount: ['transactionsCount', optional(string())],
});
