/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Auto-generated Id of service handler Swagger specification file uploaded. */
export interface ServiceSwaggerSpecId {
  /** Auto-generated id of the service handler Swagger specification file uploaded. */
  id?: string;
}

export const serviceSwaggerSpecIdSchema: Schema<ServiceSwaggerSpecId> = object({
  id: ['id', optional(string())],
});
