/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ServiceLaunchTerraformGitTag {
  tagName?: string;
  terraformPath?: string;
}

export const serviceLaunchTerraformGitTagSchema: Schema<ServiceLaunchTerraformGitTag> = object(
  {
    tagName: ['tagName', optional(string())],
    terraformPath: ['terraformPath', optional(string())],
  }
);
