/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ServiceTypeEnum
 */
export enum ServiceTypeEnum {
  MYSERVICE = 'MY_SERVICE',
  VZSERVICE = 'VZ_SERVICE',
}

/**
 * Schema for ServiceTypeEnum
 */
export const serviceTypeEnumSchema: Schema<ServiceTypeEnum> = stringEnum(ServiceTypeEnum);
