/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { ServiceInstance, serviceInstanceSchema } from './serviceInstance';

export interface ServiceInstancesResultSetItem {
  /** URL to check the status of the add service. */
  statusUrl?: string;
  /** A unique Id assigned to the request by system calling API. */
  requestId?: string;
  correlationId?: string;
  /** Status of the added service. */
  status?: string;
  /** State of the service instance. */
  state?: string;
  service?: ServiceInstance;
}

export const serviceInstancesResultSetItemSchema: Schema<ServiceInstancesResultSetItem> = object(
  {
    statusUrl: ['statusUrl', optional(string())],
    requestId: ['requestId', optional(string())],
    correlationId: ['correlationId', optional(string())],
    status: ['status', optional(string())],
    state: ['state', optional(string())],
    service: ['service', optional(lazy(() => serviceInstanceSchema))],
  }
);
