/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { DeviceList, deviceListSchema } from './deviceList';

export interface SetFallbackAttributeRequest {
  devices?: DeviceList[];
  accountName?: string;
  carrierName?: string;
}

export const setFallbackAttributeRequestSchema: Schema<SetFallbackAttributeRequest> = object(
  {
    devices: ['devices', optional(array(lazy(() => deviceListSchema)))],
    accountName: ['accountName', optional(string())],
    carrierName: ['carrierName', optional(string())],
  }
);
