/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { GIODeviceId, gIODeviceIdSchema } from './gIODeviceId';

export interface SMSEventHistoryRequest {
  deviceId: GIODeviceId;
  earliest?: string;
  latest?: string;
}

export const sMSEventHistoryRequestSchema: Schema<SMSEventHistoryRequest> = object(
  {
    deviceId: ['deviceId', lazy(() => gIODeviceIdSchema)],
    earliest: ['earliest', optional(string())],
    latest: ['latest', optional(string())],
  }
);
