/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, optional, Schema } from '../schema';
import { SMSMessage, sMSMessageSchema } from './sMSMessage';

/** Response to SMS messages sent by all M2M devices associated with a billing account. */
export interface SMSMessagesQueryResult {
  /** False for a status 200 response.True for a status 202 response, indicating that there is more data to be retrieved. */
  hasMoreData?: boolean;
  /** An array of up to 100 SMS messages that were sent by devices in the account. */
  messages?: SMSMessage[];
}

export const sMSMessagesQueryResultSchema: Schema<SMSMessagesQueryResult> = object(
  {
    hasMoreData: ['hasMoreData', optional(boolean())],
    messages: ['messages', optional(array(lazy(() => sMSMessageSchema)))],
  }
);
