/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface SMSOptionsSendRequest {
  servicePlan?: string;
  smsMessage?: string;
}

export const sMSOptionsSendRequestSchema: Schema<SMSOptionsSendRequest> = object(
  {
    servicePlan: ['servicePlan', optional(string())],
    smsMessage: ['smsMessage', optional(string())],
  }
);
