/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SourceCodeTypeEnum
 */
export enum SourceCodeTypeEnum {
  JAVA = 'JAVA',
  GO = 'GO',
}

/**
 * Schema for SourceCodeTypeEnum
 */
export const sourceCodeTypeEnumSchema: Schema<SourceCodeTypeEnum> = stringEnum(SourceCodeTypeEnum);
