/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Subrequest, subrequestSchema } from './subrequest';

export interface StatusResponse {
  requestId?: string;
  status?: string;
  subrequests?: Subrequest[];
}

export const statusResponseSchema: Schema<StatusResponse> = object({
  requestId: ['requestId', optional(string())],
  status: ['status', optional(string())],
  subrequests: ['subrequests', optional(array(lazy(() => subrequestSchema)))],
});
