/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface StorageClassMap {
  glusterFs?: string;
  hostPath?: string;
}

export const storageClassMapSchema: Schema<StorageClassMap> = object({
  glusterFs: ['GlusterFs', optional(string())],
  hostPath: ['HostPath', optional(string())],
});
