/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

/** Subscription resource definition. */
export interface Subscription {
  /** The number of streaming failures due to faulty configuration. */
  configurationfailures?: number;
  /** The number of streaming failures due to faulty configuration. */
  createdon?: string;
  /** Not currently used. */
  delegateid?: string;
  /** Description of the subscription. */
  description?: string;
  /** Whether the subscription is currently sending data. */
  disabled?: boolean;
  /** The address to which any error reports should be delivered. */
  email?: string;
  /** Filter for events. */
  filter?: string;
  /** ThingSpace unique ID for the subscription that was created. */
  id?: string;
  /** Identifies the resource kind. */
  kind?: string;
  /** Possible values: success or fail. */
  laststreamingstatus?: string;
  /** The date and time that the last stream send was attempted. */
  laststreamingtime?: string;
  /** The date the resource was last updated. */
  lastupdated?: string;
  /** Name of the subscription. */
  name?: string;
  /** The number of failures due to network problems. */
  networkfailures?: number;
  streamfailures?: number;
  /** The event type that will be sent in the data stream. */
  streamkind?: string;
  /** Target to be used for dispatching events. */
  targetid?: string;
  targettype?: string;
  /** Version of the underlying schema resource. */
  version?: string;
  /** The version of the resource. */
  versionid?: string;
}

export const subscriptionSchema: Schema<Subscription> = object({
  configurationfailures: ['configurationfailures', optional(number())],
  createdon: ['createdon', optional(string())],
  delegateid: ['delegateid', optional(string())],
  description: ['description', optional(string())],
  disabled: ['disabled', optional(boolean())],
  email: ['email', optional(string())],
  filter: ['filter', optional(string())],
  id: ['id', optional(string())],
  kind: ['kind', optional(string())],
  laststreamingstatus: ['laststreamingstatus', optional(string())],
  laststreamingtime: ['laststreamingtime', optional(string())],
  lastupdated: ['lastupdated', optional(string())],
  name: ['name', optional(string())],
  networkfailures: ['networkfailures', optional(number())],
  streamfailures: ['streamfailures', optional(number())],
  streamkind: ['streamkind', optional(string())],
  targetid: ['targetid', optional(string())],
  targettype: ['targettype', optional(string())],
  version: ['version', optional(string())],
  versionid: ['versionid', optional(string())],
});
