/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Target resource definition. */
export interface Target {
  /** The endpoint for data streams. */
  address?: string;
  /** The transport format. */
  addressscheme?: string;
  /** The billing account ID. */
  billingaccountid?: string;
  /** The date the resource was created. */
  createdon?: string;
  /** Security identification string. */
  externalid?: string;
  /** ThingSpace unique ID for the target that was created. */
  id?: string;
  /** Identifies the resource kind. Targets are ts.target. */
  kind?: string;
  /** The date the resource was last updated. */
  lastupdated?: string;
  /** Name of the target. */
  name?: string;
  /** AWS region value. */
  region?: string;
  /** Version of the underlying schema resource. */
  version?: string;
  /** The version of the resource. */
  versionid?: string;
  /** Description of the target. */
  description?: string;
}

export const targetSchema: Schema<Target> = object({
  address: ['address', optional(string())],
  addressscheme: ['addressscheme', optional(string())],
  billingaccountid: ['billingaccountid', optional(string())],
  createdon: ['createdon', optional(string())],
  externalid: ['externalid', optional(string())],
  id: ['id', optional(string())],
  kind: ['kind', optional(string())],
  lastupdated: ['lastupdated', optional(string())],
  name: ['name', optional(string())],
  region: ['region', optional(string())],
  version: ['version', optional(string())],
  versionid: ['versionid', optional(string())],
  description: ['description', optional(string())],
});
