/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TemplateTypeEnum
 */
export enum TemplateTypeEnum {
  Terraform = 'Terraform',
  Heat = 'Heat',
  CloudFormation = 'CloudFormation',
  TOSCA = 'TOSCA',
}

/**
 * Schema for TemplateTypeEnum
 */
export const templateTypeEnumSchema: Schema<TemplateTypeEnum> = stringEnum(TemplateTypeEnum);
