/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The transaction ID of the request that you want to cancel, from the POST /devicelocations synchronus response. */
export interface TransactionID {
  txid?: string;
}

export const transactionIDSchema: Schema<TransactionID> = object({
  txid: ['txid', optional(string())],
});
