/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface TriggerAttributesOptions {
  /** If present, the NotificationGroupName will be listed here. */
  key?: string;
  /** DataPercentage50<br />True - Trigger on Data percentage is over 50% used<br />False - Do not trigger when over 50% used. */
  value?: boolean;
}

export const triggerAttributesOptionsSchema: Schema<TriggerAttributesOptions> = object(
  { key: ['key', optional(string())], value: ['value', optional(boolean())] }
);
