/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TriggerV2Response {
  triggerId?: string;
}

export const triggerV2ResponseSchema: Schema<TriggerV2Response> = object({
  triggerId: ['triggerId', optional(string())],
});
