/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Notification, notificationSchema } from './notification';
import {
  TriggerAttributesOptions,
  triggerAttributesOptionsSchema,
} from './triggerAttributesOptions';
import {
  UsageAnomalyAttributes,
  usageAnomalyAttributesSchema,
} from './usageAnomalyAttributes';

export interface TriggersListOptions {
  /** The system assigned name of the trigger being updated. */
  triggerId?: string;
  /** The user defined name of the trigger. */
  triggerName?: string;
  /** The user assigned name of the organization associated with the trigger. */
  organizationName?: string;
  /** This is the value to use in the request body to detect anomalous behaivior. The values in this table will only be relevant when this parameter is set to this value. */
  triggerCategory?: string;
  /** Additional details and keys for the trigger. */
  triggerAttributes?: TriggerAttributesOptions[];
  /** Timestamp for whe the trigger was created. */
  createdAt?: string;
  /** Timestamp for the most recent time the trigger was modified. */
  modifiedAt?: string;
  /** The details of the UsageAnomaly trigger. */
  anomalyattributes?: UsageAnomalyAttributes;
  /** The notification details of the trigger. */
  notification?: Notification;
}

export const triggersListOptionsSchema: Schema<TriggersListOptions> = object({
  triggerId: ['triggerId', optional(string())],
  triggerName: ['triggerName', optional(string())],
  organizationName: ['organizationName', optional(string())],
  triggerCategory: ['triggerCategory', optional(string())],
  triggerAttributes: [
    'triggerAttributes',
    optional(array(lazy(() => triggerAttributesOptionsSchema))),
  ],
  createdAt: ['createdAt', optional(string())],
  modifiedAt: ['modifiedAt', optional(string())],
  anomalyattributes: [
    'anomalyattributes',
    optional(lazy(() => usageAnomalyAttributesSchema)),
  ],
  notification: ['notification', optional(lazy(() => notificationSchema))],
});
