/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Response to update registered Service Endpoint information. */
export interface UpdateServiceEndpointResult {
  /** HTTP status code. */
  status?: string;
  /** EdgeAppServices are updated or error details in case of an error. */
  message?: string;
}

export const updateServiceEndpointResultSchema: Schema<UpdateServiceEndpointResult> = object(
  {
    status: ['status', optional(string())],
    message: ['message', optional(string())],
  }
);
