/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Response on successful update of service profile. */
export interface UpdateServiceProfileResult {
  /** HTTP status code. */
  status?: string;
  /** Service Profile that are updated or error details in case of an error. */
  message?: string;
}

export const updateServiceProfileResultSchema: Schema<UpdateServiceProfileResult> = object(
  {
    status: ['status', optional(string())],
    message: ['message', optional(string())],
  }
);
