/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
} from '../schema';
import { FirmwareUpgrade, firmwareUpgradeSchema } from './firmwareUpgrade';

/** Upgrade information. */
export interface UpgradeListQueryResult {
  /** True if there are more devices to retrieve. */
  hasMoreFlag?: boolean;
  /** If hasMoreData=true, the startIndex to use for the next request. 0 if hasMoreData=false. */
  lastSeenUpgradeId?: number;
  /** Array of upgrade objects with the specified status. */
  reportList?: FirmwareUpgrade[] | null;
}

export const upgradeListQueryResultSchema: Schema<UpgradeListQueryResult> = object(
  {
    hasMoreFlag: ['hasMoreFlag', optional(boolean())],
    lastSeenUpgradeId: ['lastSeenUpgradeId', optional(number())],
    reportList: [
      'reportList',
      optional(nullable(array(lazy(() => firmwareUpgradeSchema)))),
    ],
  }
);
