/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface UploadConfigurationFilesResponse {
  /** The name of the file you are upgrading to. */
  fileName?: string;
  /** The version of the file you are upgrading to. */
  fileVersion?: string;
  /** Software launch date. */
  launchDate?: string;
  /** Software release note. */
  releaseNote?: string;
  /** Software applicable device model. */
  model?: string;
  /** Software applicable device make. */
  make?: string;
  /** LWM2M, OMD-DM or HTTP. */
  distributionType?: string;
  /** The platform (Android, iOS, etc.) that the software can be applied to. */
  devicePlatformId?: string;
  /** Local target path on the device. */
  localTargetPath?: string;
}

export const uploadConfigurationFilesResponseSchema: Schema<UploadConfigurationFilesResponse> = object(
  {
    fileName: ['fileName', optional(string())],
    fileVersion: ['fileVersion', optional(string())],
    launchDate: ['launchDate', optional(string())],
    releaseNote: ['releaseNote', optional(string())],
    model: ['model', optional(string())],
    make: ['make', optional(string())],
    distributionType: ['distributionType', optional(string())],
    devicePlatformId: ['devicePlatformId', optional(string())],
    localTargetPath: ['localTargetPath', optional(string())],
  }
);
