/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';
import { ServiceNameEnum, serviceNameEnumSchema } from './serviceNameEnum';

export interface UsageTriggerAddRequest {
  /** Usage trigger name */
  triggerName?: string;
  /** Account name */
  accountName: string;
  /** Service name */
  serviceName: ServiceNameEnum;
  /** The percent of subscribed usage required to activate the trigger, such as 90 or 100. */
  thresholdValue: string;
  /** Allow additional requests after thresholdValue is reached. (currently not functional) */
  allowExcess?: boolean;
  /** Send SMS (text) alerts when the thresholdValue is reached. */
  sendSmsNotification?: boolean;
  /** Comma-separated list of phone numbers to send SMS alerts to. Digits only; no dashes or parentheses, etc. */
  smsPhoneNumbers?: string;
  /** Send email alerts when the thresholdValue is reached. */
  sendEmailNotification?: boolean;
  /** Comma-separated list of email addresses to send alerts to. */
  emailAddresses?: string;
}

export const usageTriggerAddRequestSchema: Schema<UsageTriggerAddRequest> = object(
  {
    triggerName: ['triggerName', optional(string())],
    accountName: ['accountName', string()],
    serviceName: ['serviceName', serviceNameEnumSchema],
    thresholdValue: ['thresholdValue', string()],
    allowExcess: ['allowExcess', optional(boolean())],
    sendSmsNotification: ['sendSmsNotification', optional(boolean())],
    smsPhoneNumbers: ['smsPhoneNumbers', optional(string())],
    sendEmailNotification: ['sendEmailNotification', optional(boolean())],
    emailAddresses: ['emailAddresses', optional(string())],
  }
);
