/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface UsageTriggerUpdateRequest {
  /** Usage trigger name */
  triggerName?: string;
  /** Account name */
  accountName: string;
  /** The percent of subscribed usage required to activate the trigger, such as 90 or 100. */
  thresholdValue?: string;
  /** Comma-separated list of phone numbers to send SMS alerts to. Digits only; no dashes or parentheses, etc. */
  smsPhoneNumbers?: string;
  /** Comma-separated list of email addresses to send alerts to. */
  emailAddresses?: string;
}

export const usageTriggerUpdateRequestSchema: Schema<UsageTriggerUpdateRequest> = object(
  {
    triggerName: ['triggerName', optional(string())],
    accountName: ['accountName', string()],
    thresholdValue: ['thresholdValue', optional(string())],
    smsPhoneNumbers: ['smsPhoneNumbers', optional(string())],
    emailAddresses: ['emailAddresses', optional(string())],
  }
);
