/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface UsageRequestResponse {
  requestId?: string;
}

export const usageRequestResponseSchema: Schema<UsageRequestResponse> = object({
  requestId: ['requestId', optional(string())],
});
