/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

/** List of licenses assigned. */
export interface V1ListOfLicensesToRemoveResult {
  /** The total number of devices on the cancellation candidate list. */
  count?: number;
  /** The IMEIs of the devices. */
  deviceList?: string[];
}

export const v1ListOfLicensesToRemoveResultSchema: Schema<V1ListOfLicensesToRemoveResult> = object(
  {
    count: ['count', optional(number())],
    deviceList: ['deviceList', optional(array(string()))],
  }
);
