/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { V1DeviceListItem, v1DeviceListItemSchema } from './v1DeviceListItem';

/** License assignment or removal confirmation. */
export interface V1LicensesAssignedRemovedResult {
  /** Account identifier in "##########-#####". */
  accountName?: string;
  /** Total number of monthly licenses in an MRC subscription. */
  licCount?: number;
  /** Number of licenses assigned to devices after the request completed. */
  licUsedCount?: number;
  /** A JSON object for each device that was in the request. */
  deviceList?: V1DeviceListItem[];
}

export const v1LicensesAssignedRemovedResultSchema: Schema<V1LicensesAssignedRemovedResult> = object(
  {
    accountName: ['accountName', optional(string())],
    licCount: ['licCount', optional(number())],
    licUsedCount: ['licUsedCount', optional(number())],
    deviceList: [
      'deviceList',
      optional(array(lazy(() => v1DeviceListItemSchema))),
    ],
  }
);
