/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

/** List of cancellation candidate devices. */
export interface V1ListOfLicensesToRemove {
  /** The total number of devices on the list. */
  count?: number;
  /** True if there are more devices to retrieve. */
  hasMoreData?: boolean;
  /** The date and time that the list was last updated. */
  updateTime?: string;
  /** The IMEIs of the devices. */
  deviceList?: string[];
}

export const v1ListOfLicensesToRemoveSchema: Schema<V1ListOfLicensesToRemove> = object(
  {
    count: ['count', optional(number())],
    hasMoreData: ['hasMoreData', optional(boolean())],
    updateTime: ['updateTime', optional(string())],
    deviceList: ['deviceList', optional(array(string()))],
  }
);
