/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

/** IMEIs of the devices to assign licenses to. */
export interface V1LicensesAssignedRemovedRequest {
  /** The IMEIs of the devices. */
  deviceList: string[];
}

export const v1LicensesAssignedRemovedRequestSchema: Schema<V1LicensesAssignedRemovedRequest> = object(
  { deviceList: ['deviceList', array(string())] }
);
