/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Add or remove devices from the existing software upgrade information. */
export interface V2AddOrRemoveDeviceResult {
  /** Account identifier. */
  accountName: string;
  /** Campaign identifier. */
  campaignId: string;
  /** Request identifier. */
  requestId: string;
}

export const v2AddOrRemoveDeviceResultSchema: Schema<V2AddOrRemoveDeviceResult> = object(
  {
    accountName: ['accountName', string()],
    campaignId: ['campaignId', string()],
    requestId: ['requestId', string()],
  }
);
