/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { V2DeviceStatus, v2DeviceStatusSchema } from './v2DeviceStatus';

/** List of devices in a campaign. */
export interface V2CampaignDevice {
  /** Total device count. */
  totalDevice?: number;
  /** Has more report flag. */
  hasMoreData: boolean;
  /** Device identifier. */
  lastSeenDeviceId?: string;
  /** Maximum page size. */
  maxPageSize: number;
  /** List of devices with id in IMEI. */
  deviceList: V2DeviceStatus[];
}

export const v2CampaignDeviceSchema: Schema<V2CampaignDevice> = object({
  totalDevice: ['totalDevice', optional(number())],
  hasMoreData: ['hasMoreData', boolean()],
  lastSeenDeviceId: ['lastSeenDeviceId', optional(string())],
  maxPageSize: ['maxPageSize', number()],
  deviceList: ['deviceList', array(lazy(() => v2DeviceStatusSchema))],
});
