/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Device with id in IMEI. */
export interface V2DeviceStatus {
  /** Device IMEI. */
  deviceId: string;
  /** Success or failure. */
  status: string;
  /** Result reason. */
  resultReason?: string;
}

export const v2DeviceStatusSchema: Schema<V2DeviceStatus> = object({
  deviceId: ['deviceId', string()],
  status: ['status', string()],
  resultReason: ['resultReason', optional(string())],
});
