/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, Schema, string } from '../schema';

/** List of created license cancellation devices. */
export interface V2ListOfLicensesToRemoveResult {
  /** The number of devices. */
  count: number;
  /** Device IMEI list. */
  deviceList: string[];
}

export const v2ListOfLicensesToRemoveResultSchema: Schema<V2ListOfLicensesToRemoveResult> = object(
  { count: ['count', number()], deviceList: ['deviceList', array(string())] }
);
