/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

/** Allowed start and end time windows. */
export interface V2TimeWindow {
  /** Start hour in range [0..23], current hour >= startTime. */
  startTime: number;
  /** End hour in range [1..24], current hour < endTime. */
  endTime: number;
}

export const v2TimeWindowSchema: Schema<V2TimeWindow> = object({
  startTime: ['startTime', number()],
  endTime: ['endTime', number()],
});
