/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

/** Devices to add or remove from existing software upgrade information. */
export interface V3AddOrRemoveDeviceRequest {
  /** Operation either 'append' or 'remove' */
  type: string;
  /** Device IMEI list. */
  deviceList: string[];
}

export const v3AddOrRemoveDeviceRequestSchema: Schema<V3AddOrRemoveDeviceRequest> = object(
  { type: ['Type', string()], deviceList: ['deviceList', array(string())] }
);
