/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { V3TimeWindow, v3TimeWindowSchema } from './v3TimeWindow';

/** Campaign dates and time windows. */
export interface V3ChangeCampaignDatesRequest {
  /** Campaign start date. */
  startDate: string;
  /** Campaign end date. */
  endDate: string;
  /** List of allowed campaign time windows. */
  campaignTimeWindowList?: V3TimeWindow[];
}

export const v3ChangeCampaignDatesRequestSchema: Schema<V3ChangeCampaignDatesRequest> = object(
  {
    startDate: ['startDate', string()],
    endDate: ['endDate', string()],
    campaignTimeWindowList: [
      'campaignTimeWindowList',
      optional(array(lazy(() => v3TimeWindowSchema))),
    ],
  }
);
