/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Device status. */
export interface V3DeviceStatus {
  /** Device IMEI. */
  deviceId: string;
  /** Success or failure. */
  status: string;
  /** Result reason. */
  resultReason?: string;
  /** Updated Time. */
  updatedTime?: string;
  /** The most recent attempt time. */
  recentAttemptTime?: string;
  /** Next attempt time. */
  nextAttemptTime?: string;
}

export const v3DeviceStatusSchema: Schema<V3DeviceStatus> = object({
  deviceId: ['deviceId', string()],
  status: ['status', string()],
  resultReason: ['resultReason', optional(string())],
  updatedTime: ['updatedTime', optional(string())],
  recentAttemptTime: ['recentAttemptTime', optional(string())],
  nextAttemptTime: ['nextAttemptTime', optional(string())],
});
