/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Device changed. */
export interface V3DeviceListItem {
  /** Device IMEI. */
  deviceId?: string;
  /** Success or failure. */
  status?: string;
  /** Result reason. */
  reason?: string;
}

export const v3DeviceListItemSchema: Schema<V3DeviceListItem> = object({
  deviceId: ['deviceId', optional(string())],
  status: ['status', optional(string())],
  reason: ['Reason', optional(string())],
});
