/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema';
import { V3DeviceStatus, v3DeviceStatusSchema } from './v3DeviceStatus';

/** License assignment/removal response. */
export interface V3LicenseAssignedRemovedResult {
  /** Account name. */
  accountName: string;
  /** Total license count. */
  licCount: number;
  /** Assigned license count. */
  licUsedCount: number;
  /** List of devices with id in IMEI. */
  deviceList: V3DeviceStatus[];
}

export const v3LicenseAssignedRemovedResultSchema: Schema<V3LicenseAssignedRemovedResult> = object(
  {
    accountName: ['accountName', string()],
    licCount: ['licCount', number()],
    licUsedCount: ['licUsedCount', number()],
    deviceList: ['deviceList', array(lazy(() => v3DeviceStatusSchema))],
  }
);
