/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { CloudProviderEnum, cloudProviderEnumSchema } from './cloudProviderEnum';
import {
  EdgeServiceRepository,
  edgeServiceRepositorySchema,
} from './edgeServiceRepository';
import { Revision, revisionSchema } from './revision';
import { TemplateTypeEnum, templateTypeEnumSchema } from './templateTypeEnum';

export interface VirtualMachine {
  repository: EdgeServiceRepository;
  revision?: Revision;
  /** Type of the template to be used for deployment. */
  templateType: TemplateTypeEnum;
  values?: EdgeServiceRepository;
  /** Cloud provider where you plan to provision and operate your Kubernetes cluster. */
  provider?: CloudProviderEnum;
}

export const virtualMachineSchema: Schema<VirtualMachine> = object({
  repository: ['repository', lazy(() => edgeServiceRepositorySchema)],
  revision: ['revision', optional(lazy(() => revisionSchema))],
  templateType: ['templateType', templateTypeEnumSchema],
  values: ['values', optional(lazy(() => edgeServiceRepositorySchema))],
  provider: ['provider', optional(cloudProviderEnumSchema)],
});
