/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for WorkloadTypeEnum
 */
export enum WorkloadTypeEnum {
  Container = 'container',
  VirtualMachine = 'virtualMachine',
}

/**
 * Schema for WorkloadTypeEnum
 */
export const workloadTypeEnumSchema: Schema<WorkloadTypeEnum> = stringEnum(WorkloadTypeEnum);
