/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for WorkloadUploadTypeEnum
 */
export enum WorkloadUploadTypeEnum {
  PULLFROMREPO = 'PULL_FROM_REPO',
  MANUALUPLOAD = 'MANUAL_UPLOAD',
}

/**
 * Schema for WorkloadUploadTypeEnum
 */
export const workloadUploadTypeEnumSchema: Schema<WorkloadUploadTypeEnum> = stringEnum(WorkloadUploadTypeEnum);
