/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for WorkloadRepositoryTypeEnum
 */
export enum WorkloadRepositoryTypeEnum {
  GIT = 'GIT',
  HELM = 'HELM',
}

/**
 * Schema for WorkloadRepositoryTypeEnum
 */
export const workloadRepositoryTypeEnumSchema: Schema<WorkloadRepositoryTypeEnum> = stringEnum(WorkloadRepositoryTypeEnum);
