/**
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ZoneItem {
  /** Zone name. */
  zone?: string;
}

export const zoneItemSchema: Schema<ZoneItem> = object({
  zone: ['zone', optional(string())],
});
